#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['果报'] = {
 'en': "The result called forth by past karmic causes. Also termed maturation, ripening of fruit, retributive fruit, or matured fruit (vipāka). It is of two kinds: (1) General retribution\u2014the fruit that comes from the \u201cimpelling karma\u201d (the karma of general retribution); for example, a person's very existence comes from the impelling karma of a former life. (2) Particular retribution\u2014each person's individual fruit, coming from the \u201ccompleting karma\u201d (the karma of particular retribution), also called the completing fruit; thus even those born alike as humans differ as male or female, beautiful or ugly, poor or rich\u2014this is particular retribution. In terms of time, there are the three periods of karma with their three periods of retribution: (1) retribution ripening in the present\u2014karma made in this life reaps its fruit in this life (also called present retribution); (2) retribution ripening in the next birth\u2014karma made in this life reaps its fruit in the next life; (3) retribution ripening in a later life\u2014karma made in this life reaps its fruit in a still later life. Among the six destinies, the human and heavenly destinies are the fruit obtained by keeping the five precepts and practicing the ten wholesome deeds, hence called wholesome fruit; yet this wholesome fruit still involves delusion and affliction, so it is also called the \u201ctopsy-turvy wholesome fruit.\u201d",
 'fr': "Le résultat appelé par les causes karmiques passées. Aussi nommé maturation, mûrissement du fruit, fruit rétributif ou fruit mûri (vipāka). Il est de deux sortes : (1) La rétribution générale\u2014le fruit venant du « karma impulseur » (karma de rétribution générale) ; par exemple, l'existence même d'une personne vient du karma impulseur d'une vie antérieure. (2) La rétribution particulière\u2014le fruit individuel de chacun, venant du « karma achevant » (karma de rétribution particulière), aussi appelé fruit d'achèvement ; ainsi, même nés pareillement humains, on diffère selon le sexe, la beauté ou la laideur, la pauvreté ou la richesse\u2014c'est la rétribution particulière. Quant au temps, il y a les trois périodes de karma avec leurs trois périodes de rétribution : (1) rétribution mûrissant dans le présent\u2014le karma fait en cette vie porte son fruit en cette vie (aussi appelée rétribution présente) ; (2) rétribution mûrissant à la prochaine naissance\u2014le karma fait en cette vie porte son fruit à la vie suivante ; (3) rétribution mûrissant en une vie ultérieure\u2014le karma fait en cette vie porte son fruit en une vie encore plus tardive. Parmi les six destinées, celles des humains et des dieux sont le fruit obtenu en gardant les cinq préceptes et en pratiquant les dix actes salutaires, d'où le nom de fruit salutaire ; pourtant ce fruit salutaire comporte encore illusion et affliction, d'où le nom de « fruit salutaire à l'envers ».",
 'vi': "Tức kết quả do nghiệp nhân quá khứ chiêu cảm. Còn gọi là dị thục, quả thục, báo quả, dị thục quả (vipāka). Có hai thứ: (1) Tổng báo, tức quả báo do dẫn nghiệp (tổng báo nghiệp) mà đến, như sự sinh tồn của con người là do dẫn nghiệp đời trước mà có. (2) Biệt báo, tức quả báo riêng của mỗi người, do mãn nghiệp (biệt báo nghiệp) mà đến, còn gọi mãn quả; như cùng sinh làm người, mà có phân nam nữ, đẹp xấu, nghèo giàu, đó là biệt báo. Về mặt thời gian thì có ba thời báo của ba thời nghiệp: (1) thuận hiện báo, tức đời nay tạo nghiệp, đời nay chịu quả báo (còn gọi hiện báo); (2) thuận sinh báo, tức đời nay tạo nghiệp, đời sau chịu quả báo; (3) thuận hậu báo, tức đời nay tạo nghiệp, đời sau nữa mới chịu quả báo. Trong sáu đường, hai đường người và trời là quả báo do giữ năm giới, hành mười thiện mà được, nên gọi là thiện quả. Nhưng thiện quả này vẫn còn mê mờ phiền não, nên cũng gọi là điên đảo thiện quả.",
}

D['唯识三十颂'] = {
 'en': "In one fascicle. Composed by the bodhisattva Vasubandhu, translated by the Tang Tripiṭaka-master Xuanzang. Also called the Treatise in Thirty Verses on Consciousness-Only, the Verses of the Thirty-Verse Treatise, the Thirty-Verse Treatise on Consciousness-Only, and so on. Among the \u201cone root and ten branches\u201d it is called the \u201cbranch that raises high the Dharma-banner.\u201d In his late years Vasubandhu composed the thirty verses, but passed away before composing a prose commentary; thereafter the ten great commentator-masters\u2014Bandhuśrī, Citrabhāna, and others\u2014each composed a commentary on the thirty verses. When Xuanzang traveled to study in India, he brought back the commentaries of the ten houses, and blending their works he translated them as the Cheng weishi lun (Treatise on the Establishment of Consciousness-Only).",
 'fr': "En un fascicule. Composé par le bodhisattva Vasubandhu, traduit par le maître du Tripiṭaka Xuanzang, sous les Tang. Aussi appelé Traité en trente stances sur le Rien-que-conscience, Stances du Traité en trente stances, Traité des Trente sur le Rien-que-conscience, etc. Parmi « une racine et dix branches », il est appelé la « branche qui dresse haut la bannière du Dharma ». Vers la fin de sa vie, Vasubandhu composa les trente stances, mais s'éteignit avant d'en composer le commentaire en prose ; par la suite, les dix grands maîtres commentateurs\u2014Bandhuśrī, Citrabhāna et d'autres\u2014composèrent chacun un commentaire des trente stances. Lorsque Xuanzang voyagea en Inde pour étudier, il rapporta les commentaires des dix maisons et, les fondant ensemble, les traduisit sous le titre de Cheng weishi lun (Traité de l'établissement du Rien-que-conscience).",
 'vi': "Gồm một quyển. Do Bồ Tát Thế Thân tạo, Tam Tạng Huyền Trang đời Đường dịch. Còn gọi là Duy Thức Tam Thập Luận, Duy Thức Tam Thập Luận Tụng, Tam Thập Duy Thức Luận v.v. Trong “một gốc mười nhánh” gọi là “cao kiến pháp tràng chi”. Thế Thân lúc tuổi già tạo ba mươi tụng, chưa tạo thích luận thì viên tịch; sau đó mười vị đại luận sư như Thân Thắng, Hỏa Biện v.v. mỗi vị vì ba mươi tụng mà tạo thích luận. Huyền Trang du học Ấn Độ, đem thích luận của mười nhà mang về nước, nhu hợp trước tác của mười nhà mà dịch thành Thành Duy Thức Luận.",
}

D['无为法'] = {
 'en': "Among the Five Categories and Hundred Dharmas, the fifth category is the unconditioned dharmas. The Treatise on the Hundred Dharmas says: \u201cFifth, the unconditioned dharmas, briefly of six kinds: (1) unconditioned space, (2) unconditioned cessation through discrimination, (3) unconditioned cessation not through discrimination, (4) unconditioned immovability, (5) unconditioned cessation of perception-and-feeling, (6) unconditioned suchness.\u201d The unconditioned dharmas are the true dharma-nature of the preceding four categories, hence called the \u201ctrue nature of consciousness\u201d\u2014that is, the fifth, \u201cconsciousness-only as true nature.\u201d Within the Five Categories, the six divisions of mental factors are the concomitants of consciousness, called \u201cconcomitant consciousness-only\u201d; the eleven form dharmas are the objects of consciousness, called \u201cobjective consciousness-only\u201d; the twenty-four dharmas not concomitant with mind are the positional states of consciousness, called \u201cpositional consciousness-only\u201d; and the unconditioned dharmas are the true nature of consciousness, hence called \u201ctrue-nature consciousness-only.\u201d",
 'fr': "Parmi les Cinq Catégories et Cent Dharmas, la cinquième catégorie est celle des dharmas inconditionnés. Le Traité des Cent Dharmas dit : « Cinquièmement, les dharmas inconditionnés, brièvement de six sortes : (1) l'espace inconditionné, (2) la cessation inconditionnée par discrimination, (3) la cessation inconditionnée sans discrimination, (4) l'immobilité inconditionnée, (5) la cessation inconditionnée de la perception-et-sensation, (6) l'ainsité inconditionnée. » Les dharmas inconditionnés sont la véritable nature-de-dharma des quatre catégories précédentes, d'où le nom de « nature véritable de la conscience »\u2014c'est-à-dire le cinquième, « le Rien-que-conscience comme nature véritable ». Au sein des Cinq Catégories, les six divisions de facteurs mentaux sont les concomitants de la conscience (« Rien-que-conscience concomitant ») ; les onze dharmas-forme sont les objets de la conscience (« Rien-que-conscience objectif ») ; les vingt-quatre dharmas non concomitants sont les états positionnels de la conscience (« Rien-que-conscience positionnel ») ; et les dharmas inconditionnés sont la nature véritable de la conscience, d'où « Rien-que-conscience de nature véritable ».",
 'vi': "Trong Ngũ vị bách pháp, vị pháp thứ năm là vô vi pháp. Bách Pháp Minh Môn Luận nói: “Thứ năm vô vi pháp, lược có sáu thứ: (1) hư không vô vi, (2) trạch diệt vô vi, (3) phi trạch diệt vô vi, (4) bất động vô vi, (5) tưởng thọ diệt vô vi, (6) chân như vô vi.” Vô vi pháp là pháp tính chân thật của bốn vị pháp trước, nên gọi là thức thực tính, tức đệ ngũ thực tính duy thức. Trong năm vị pháp, sáu vị tâm sở là tương ưng của thức, gọi tương ưng duy thức; mười một sắc pháp là sở duyên của thức, gọi sở duyên duy thức; hai mươi bốn bất tương ưng hành là phân vị của thức, gọi phân vị duy thức; còn vô vi pháp là thực tính của thức, nên gọi thực tính duy thức.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_B4 →', len(D))
