#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['八识'] = {
 'en': "The first category among the Five Categories and Hundred Dharmas established by the Consciousness-Only school: the eight ruling minds (citta-rāja), abbreviated as the \u201ceight consciousnesses\u201d\u2014the eye, ear, nose, tongue, body, mental (mano-vijñāna), manas, and ālaya consciousnesses. The first six are named after the faculty each depends on; the manas is \u201cmind\u201d and is named after its own nature; the ālaya, in the sense of grasping and maintaining the causes and effects of all dharmas, is likewise named from its own nature. The first five are called the first five consciousnesses, the mental consciousness the sixth, the manas the seventh, and the ālaya the eighth. Since the consciousnesses from the eye up to the manas arise from the ālaya, they are collectively called the evolving consciousnesses (or seven evolving consciousnesses); the ālaya, being their cause, is called the root consciousness or seed consciousness. In the Thirty Verses the eight are divided into three transformers: the ālaya is the first transformer, the manas the second, the first six the third. As to nature: the first six take discernment as their nature, cognize the six objects (form, sound, smell, taste, touch, dharmas), and pertain to all three moral natures (good, evil, neutral); the manas takes constant deliberation as its nature, is of obscuring-neutral nature, and takes only the perceiving-portion of the ālaya as its inner self; the ālaya is of non-obscuring-neutral nature and, with a subtle mode of activity, cognizes the receptacle-world, the seeds, and the sentient body-with-faculties that it itself manifests. See the Baifa wenda chao.",
 'fr': "La première catégorie parmi les Cinq Catégories et Cent Dharmas établies par l'école du Rien-que-conscience : les huit esprits-rois (citta-rāja), abrégés en « huit consciences »\u2014les consciences de l'œil, de l'oreille, du nez, de la langue, du corps, la conscience mentale (mano-vijñāna), le manas et l'ālaya. Les six premières sont nommées d'après la faculté dont chacune dépend ; le manas est le « mental » et est nommé d'après sa propre nature ; l'ālaya, au sens de saisir et maintenir les causes et effets de tous les dharmas, est de même nommé d'après sa propre nature. Les cinq premières sont appelées les cinq premières consciences, la conscience mentale la sixième, le manas la septième, l'ālaya la huitième. Comme les consciences depuis l'œil jusqu'au manas surgissent de l'ālaya, on les nomme collectivement consciences évoluantes (ou sept consciences évoluantes) ; l'ālaya, étant leur cause, est appelé conscience-racine ou conscience-semences. Dans les Trente Stances, les huit sont réparties en trois transformateurs : l'ālaya est le premier, le manas le deuxième, les six premières le troisième. Quant à leur nature : les six premières ont pour nature le discernement, connaissent les six objets (forme, son, odeur, saveur, toucher, dharmas) et relèvent des trois natures morales (bon, mauvais, neutre) ; le manas a pour nature la délibération constante, est de nature neutre-obscurcissante et ne prend pour soi intérieur que la portion percevante de l'ālaya ; l'ālaya est de nature neutre-non-obscurcissante et, par un mode d'activité subtil, connaît le monde-réceptacle, les semences et le corps doté de facultés qu'il manifeste lui-même. Voir le Baifa wenda chao.",
 'vi': "Vị pháp thứ nhất trong Ngũ vị bách pháp do Duy Thức tông lập: tám tâm vương (citta-rāja), gọi tắt là “tám thức”\u2014nhãn, nhĩ, tỷ, thiệt, thân, ý (mano-vijñāna), mạt-na và a-lại-da. Trong đó sáu thức trước được đặt tên theo căn mà mỗi thức nương tựa; mạt-na tức là “ý”, đặt tên theo tự tính của nó; a-lại-da theo nghĩa nhiếp trì nhân quả của các pháp, cũng đặt tên từ tự tính. Năm thức đầu gọi là tiền ngũ thức, ý thức là thức thứ sáu, mạt-na là thức thứ bảy, a-lại-da là thức thứ tám. Vì các thức từ nhãn đến mạt-na đều do a-lại-da sinh khởi, nên gọi chung là chuyển thức (hay bảy chuyển thức); a-lại-da là nhân của chúng nên gọi là căn bản thức, chủng tử thức. Trong Duy Thức Tam Thập Tụng, tám thức chia thành ba năng biến: a-lại-da là sơ năng biến, mạt-na là đệ nhị năng biến, sáu thức trước là đệ tam năng biến. Về tính: sáu thức trước lấy liễu biệt làm tính, duyên sáu cảnh (sắc, thanh, hương, vị, xúc, pháp), thông cả ba tính thiện, ác, vô ký; mạt-na lấy hằng thẩm tư lương làm tính, thuộc hữu phú vô ký, chỉ duyên kiến phần của a-lại-da làm nội ngã của mình; a-lại-da thuộc vô phú vô ký, với hành tướng vi tế duyên khí giới, chủng tử và hữu căn thân do chính nó biến hiện. Xem Bách Pháp Vấn Đáp Sao.",
}

D['八识规矩颂'] = {
 'en': "Comprising four sections, twelve verses, forty-eight lines. Composed by the Tang-dynasty Tripiṭaka-master Xuanzang. It summarizes the Consciousness-Only teaching, focusing on the question of mind-and-consciousness that lies at its heart. The first three verses treat the first five consciousnesses; verses four to six the sixth consciousness; verses seven to nine the seventh consciousness; the last three verses the eighth consciousness. Commentaries are numerous, the more famous being Putai's Supplementary Notes on the Verses (Ming), Mingyu's Correct Meaning of the Supplementary Notes, Zhixu's Direct Explanation of the Verses, and Guangyi's Compiled Explanation of the Verses.",
 'fr': "Composé de quatre sections, douze stances, quarante-huit vers. Rédigé par le maître du Tripiṭaka Xuanzang, sous les Tang. Il résume la doctrine du Rien-que-conscience, en insistant sur la question du mental-et-conscience qui en est le cœur. Les trois premières stances traitent des cinq premières consciences ; les stances quatre à six, de la sixième conscience ; les stances sept à neuf, de la septième ; les trois dernières, de la huitième. Les commentaires sont nombreux, les plus célèbres étant les Notes supplémentaires de Putai (Ming), le Sens correct des Notes supplémentaires de Mingyu, l'Explication directe de Zhixu et l'Explication compilée de Guangyi.",
 'vi': "Gồm bốn chương, mười hai tụng, bốn mươi tám câu. Do Tam Tạng Huyền Trang đời Đường soạn. Khái quát học thuyết Duy Thức, chú trọng thuyết minh vấn đề tâm thức\u2014trung tâm của Duy Thức học. Ba tụng đầu nói về tiền ngũ thức, tụng bốn đến sáu nói về thức thứ sáu, tụng bảy đến chín nói về thức thứ bảy, ba tụng cuối nói về thức thứ tám. Bản chú thích rất nhiều, nổi tiếng hơn cả là Bát Thức Quy Củ Bổ Chú của Phổ Thái (đời Minh), Bổ Chú Chính Nghĩa của Minh Dục, Trực Giải của Trí Húc, và Toản Thích của Quảng Ích.",
}

D['三乘'] = {
 'en': "\u201cVehicle\u201d means a conveyance; the Three Vehicles are three kinds of conveyance, a metaphor for the three teachings that carry sentient beings across the stream of birth-and-death to the far shore of nirvāṇa. In accordance with beings' differing capacities, the Buddha taught three: the Śrāvaka Vehicle, the Pratyekabuddha Vehicle, and the Bodhisattva Vehicle. (1) The Śrāvaka Vehicle: awakening to the Way by hearing the Buddha's spoken teaching, hence \u201cvoice-hearer\u201d; knowing suffering and cutting off its origin, longing for cessation and cultivating the path, they take these Four Truths as their vehicle. (2) The Pratyekabuddha Vehicle (also \u201csolitary-awakened\u201d): awakening to the true principle by contemplating the twelve links of dependent origination, hence \u201ccondition-awakened\u201d; first contemplating ignorance through old-age-and-death, then the cessation of ignorance through the cessation of old-age-and-death, and thereby awakening to what is neither arising nor ceasing, they take these twelve links as their vehicle. (3) The Bodhisattva Vehicle (also the Great Vehicle, the Buddha Vehicle): seeking supreme enlightenment, vowing to deliver all beings, cultivating the six perfections and myriad practices, they take these six perfections as their vehicle. The first two vehicles benefit only oneself and not others, so they are together called the Lesser Vehicle; the Bodhisattva Vehicle fully possesses both self-benefit and benefit for others, so it is the Great Vehicle.",
 'fr': "« Véhicule » signifie moyen de transport ; les Trois Véhicules sont trois sortes de véhicules, métaphore des trois enseignements qui transportent les êtres à travers le courant des naissances et des morts jusqu'à l'autre rive du nirvāṇa. Selon les capacités différentes des êtres, le Buddha enseigna trois véhicules : celui des Auditeurs (Śrāvaka), celui des Bouddhas-pour-soi (Pratyekabuddha) et celui des Bodhisattvas. (1) Le Véhicule des Auditeurs : s'éveiller à la Voie en entendant l'enseignement oral du Buddha, d'où « auditeur » ; connaissant la souffrance et tranchant son origine, aspirant à la cessation et cultivant la voie, ils prennent ces Quatre Vérités pour véhicule. (2) Le Véhicule des Pratyekabuddha (aussi « éveillés solitaires ») : s'éveiller au principe véritable en contemplant les douze liens de la coproduction conditionnée, d'où « éveillé-par-les-conditions » ; contemplant d'abord l'ignorance jusqu'à la vieillesse-et-mort, puis la cessation de l'ignorance jusqu'à la cessation de la vieillesse-et-mort, ils s'éveillent au ni-naître ni-cesser et prennent ces douze liens pour véhicule. (3) Le Véhicule des Bodhisattvas (aussi Grand Véhicule, Véhicule du Buddha) : recherchant l'éveil suprême, faisant vœu de délivrer tous les êtres, cultivant les six perfections et les innombrables pratiques, ils prennent ces six perfections pour véhicule. Les deux premiers véhicules ne profitent qu'à soi et non à autrui : on les nomme ensemble Petit Véhicule ; le Véhicule des Bodhisattvas possède pleinement le bénéfice de soi et d'autrui : c'est le Grand Véhicule.",
 'vi': "“Thừa” nghĩa là phương tiện chuyên chở; Tam thừa là ba loại phương tiện, ví dụ cho ba pháp môn chở chúng sinh vượt dòng sinh tử đến bờ kia niết-bàn. Tùy căn cơ chúng sinh khác nhau, đức Phật ứng theo mà nói ba giáo pháp: Thanh Văn thừa, Duyên Giác thừa, Bồ Tát thừa. (1) Thanh Văn thừa: nghe âm thanh giáo pháp của Phật mà ngộ đạo, nên gọi là Thanh Văn; biết khổ đoạn tập, mộ diệt tu đạo, lấy Tứ đế này làm thừa. (2) Duyên Giác thừa (còn gọi Bích-chi-phật thừa, Độc Giác thừa): quán mười hai nhân duyên mà giác ngộ lý chân đế, nên gọi là Duyên Giác; trước quán vô minh cho đến lão tử, kế quán vô minh diệt cho đến lão tử diệt, do sinh diệt của nhân duyên ấy mà ngộ được phi sinh phi diệt, lấy mười hai nhân duyên này làm thừa. (3) Bồ Tát thừa (còn gọi Đại thừa, Phật thừa): cầu vô thượng bồ-đề, nguyện độ hết thảy chúng sinh, tu sáu độ muôn hạnh, lấy sáu độ này làm thừa. Hai thừa trước chỉ tự lợi, không lợi tha, nên gọi chung là Tiểu thừa; Bồ Tát thừa đầy đủ cả tự lợi lợi tha, nên là Đại thừa.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_A1 合并后 defs_i18n.json 共', len(D), '条')
