#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['戒波罗蜜'] = {
 'en': "It signifies conduct, habit, character, morality, and reverent devotion. It is one of the three trainings, one of the six perfections, and one of the ten perfections. In cultivating the Consciousness-Only practice and entering the path of cultivation, one practices the ten excellent practices, which are the ten perfections; the second of these is the perfection of moral discipline. Discipline (śīla) is of three kinds: (1) the discipline of restraining regulations\u2014strictly keeping the precepts and rules so as to prevent transgression; (2) the discipline of embracing wholesome dharmas\u2014upholding all the wholesome dharmas that should be cultivated and realized; (3) the discipline of benefiting sentient beings\u2014relieving beings' sufferings and bringing them benefit and joy. See the entry \u201cten perfections.\u201d",
 'fr': "Il signifie la conduite, l'habitude, le caractère, la moralité et la dévotion révérencieuse. C'est l'une des trois disciplines, l'une des six perfections et l'une des dix perfections. En cultivant la pratique du Rien-que-conscience et en entrant dans la voie de la culture, on pratique les dix pratiques excellentes, qui sont les dix perfections ; la deuxième d'entre elles est la perfection de la discipline morale. La discipline (śīla) est de trois sortes : (1) la discipline des règles de restreinte\u2014garder strictement les préceptes et règles afin de prévenir la transgression ; (2) la discipline embrassant les dharmas salutaires\u2014maintenir tous les dharmas salutaires qu'il faut cultiver et réaliser ; (3) la discipline bénéfique aux êtres\u2014soulager les souffrances des êtres et leur apporter bienfait et joie. Voir l'entrée « dix perfections ».",
 'vi': "Chỉ hành vi, tập quán, tính cách, đạo đức, kiền thành. Là một trong ba học, một trong sáu ba-la-mật, một trong mười ba-la-mật. Tu Duy Thức hạnh, vào tu đạo vị, tu mười thắng hạnh, mười thắng hạnh chính là mười ba-la-mật-đa. Trong đó thứ hai là giới ba-la-mật-đa. Giới có ba thứ: (1) luật nghi giới, tức nghiêm giữ giới luật nghi tắc để phòng ngừa lỗi quấy; (2) nhiếp thiện pháp giới, tức nhiếp trì hết thảy thiện pháp nên tu nên chứng; (3) nhiêu ích hữu tình giới, tức cứu vớt các khổ, lợi lạc hữu tình. Tham khảo “mười ba-la-mật-đa”.",
}

D['身口意三业'] = {
 'en': "Refers to the fabricating activity of the three\u2014body, speech, and mind\u2014called the three karmas. (1) Bodily karma: karma issuing from all movements of the body, of two sorts\u2014manifest bodily karma and unmanifest karma. (2) Verbal karma: karma issuing from the fabrications of the mouth. (3) Mental karma: karma issuing from the deliberation of the sixth consciousness, which is the function of the mental factor of volition (cetanā). As the Cheng weishi lun says of the factor of volition: \u201cIts nature is to make the mind fabricate; its function is to direct the mind toward the wholesome and the like.\u201d Hence mental karma is also called \u201cvolitional karma.\u201d The intrinsic nature of volition is simply fabrication; thus by the power of its fabrication it corresponds with the consciousnesses and drives them to fabricate the wholesome, the unwholesome, the neutral, and so forth. The \u201cconsciousness\u201d here refers to the sixth, mental, consciousness together with its concomitant mental factors.",
 'fr': "Désigne l'activité fabricatrice des trois\u2014corps, parole et mental\u2014appelée les trois karmas. (1) Karma corporel : karma issu de tous les mouvements du corps, de deux sortes\u2014karma corporel manifeste et karma non manifesté. (2) Karma verbal : karma issu des fabrications de la bouche. (3) Karma mental : karma issu de la délibération de la sixième conscience, qui est la fonction du facteur mental de volition (cetanā). Comme le dit le Cheng weishi lun du facteur de volition : « Sa nature est de faire fabriquer l'esprit ; sa fonction est de diriger l'esprit vers le salutaire et le reste. » D'où le nom de « karma volitionnel » donné au karma mental. La nature propre de la volition est simplement la fabrication ; ainsi, par la force de sa fabrication, elle correspond aux consciences et les pousse à fabriquer le salutaire, le non-salutaire, le neutre, etc. La « conscience » ici désigne la sixième conscience mentale avec ses facteurs mentaux concomitants.",
 'vi': "Chỉ sự tạo tác của ba thứ thân, khẩu, ý, gọi là tam nghiệp: (1) Thân nghiệp: nghiệp phát ra từ hết thảy động tác của thân, có hai thứ\u2014thân biểu nghiệp và vô biểu nghiệp. (2) Khẩu nghiệp: nghiệp phát ra từ sự tạo tác nơi miệng. (3) Ý nghiệp: nghiệp phát ra từ tư duy của thức thứ sáu, đó là tác dụng của tâm sở tư (cetanā). Như Thành Duy Thức Luận nói về tâm sở tư: “Tính là khiến tâm tạo tác, nghiệp là sai khiến tâm nơi các phẩm thiện v.v.” Nên ý nghiệp còn gọi là tư nghiệp. Tự tính của tư chỉ là tạo tác, nên có thể lấy lực dụng tạo tác của nó tương ưng với tâm thức, sai khiến tâm thức khởi các tạo tác thiện, ác, vô ký v.v. Tâm thức nói trên chỉ thức thứ sáu ý thức, và bao gồm tâm sở tương ưng của nó.",
}

D['法无我'] = {
 'en': "One of the two selflessnesses, the counterpart of \u201cselflessness of persons.\u201d It means that within all dharmas, conditioned and unconditioned, there is no substantial \u201cself.\u201d That is, all dharmas arise dependent on causes and conditions, are mutually dependent, and lack any substantial nature: conditioned dharmas have function yet do not abide permanently; unconditioned dharmas abide permanently yet have no function. \u201cAll dharmas are without self\u201d is also one of the three Dharma-seals, called the seal \u201call dharmas are without self\u201d; the three Dharma-seals are a crucial teaching of the Buddha-Dharma, and whether a teaching is ultimate is verified by these three. To understand that all dharmas arise from causes and conditions and truly have no self-nature or substance is the bodhisattva's path of contemplation, whereby one severs the hindrance to the knowable. The wisdom that thoroughly comprehends this principle is called the wisdom of the two selflessnesses.",
 'fr': "L'une des deux absences-de-soi, pendant de l'« absence-de-soi des personnes ». Cela signifie qu'au sein de tous les dharmas, conditionnés et inconditionnés, il n'y a pas de « soi » substantiel. C'est-à-dire que tous les dharmas naissent en dépendance de causes et conditions, sont mutuellement dépendants et dépourvus de nature substantielle : les dharmas conditionnés ont une fonction mais ne demeurent pas de façon permanente ; les dharmas inconditionnés demeurent de façon permanente mais n'ont pas de fonction. « Tous les dharmas sont sans soi » est aussi l'un des trois sceaux du Dharma, appelé le sceau « tous les dharmas sont sans soi » ; les trois sceaux sont un enseignement crucial du Dharma, et c'est par eux que l'on vérifie si un enseignement est ultime. Comprendre que tous les dharmas naissent des causes et conditions et n'ont véritablement ni nature propre ni substance est la voie de contemplation du bodhisattva, par laquelle on tranche l'obstacle au connaissable. La sagesse qui pénètre à fond ce principe est appelée la sagesse des deux absences-de-soi.",
 'vi': "Một trong hai vô ngã, đối lại với “nhân vô ngã”. Nghĩa là trong hết thảy pháp hữu vi, vô vi, đều không có thực thể “ngã”. Tức hết thảy pháp đều nương nhân duyên mà sinh, nương tựa lẫn nhau, không có thực thể tính: hữu vi pháp tuy có tác dụng nhưng không thường trụ; vô vi pháp tuy thường trụ nhưng không có tác dụng. Lại “chư pháp vô ngã” là một trong ba pháp ấn, gọi là chư pháp vô ngã ấn; ba pháp ấn là giáo nghĩa quan trọng của Phật pháp, phán định Phật pháp có rốt ráo hay không đều lấy ba cái này ấn chứng. Rõ biết các pháp do nhân duyên sinh, thật không có tự tính thực thể, đó là quán đạo của Bồ Tát Đại thừa, do đó đoạn sở tri chướng. Trí tuệ thấu suốt lý này gọi là nhị vô ngã trí.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_B3 →', len(D))
