#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['色法'] = {
 'en': "The counterpart of \u201cmind dharmas.\u201d All dharmas are divided into the three schemata of aggregates, bases, and elements, taking the five aggregates as basic; the five aggregates, further condensed, are just the two dharmas of form and mind. \u201cForm dharma,\u201d broadly speaking, is the general term for material existence, referring to whatever has the nature of resistance\u2014that is, whatever occupies a definite space, mutually obstructs self and other, and is liable to deterioration. If all dharmas are classified by the Five Categories and Hundred Dharmas, they divide into form dharmas, mind dharmas, mental-factor dharmas, dharmas not concomitant with mind, and unconditioned dharmas. Among these, form dharma is called the \u201cform aggregate\u201d in the five-aggregate classification, and mind dharma the \u201cconsciousness aggregate.\u201d In the Consciousness-Only school's Five Categories and Hundred Dharmas, form dharmas are divided into three classes and eleven kinds: (1) the five faculties of eye, ear, nose, tongue, and body; (2) the five objects of form, sound, smell, taste, and touch; (3) unmanifest form. Within the Five Categories, form dharmas are placed after mind dharmas and mental-factor dharmas, because they cannot arise independently but are merely the manifestations of these former two.",
 'fr': "Le pendant des « dharmas-esprit ». Tous les dharmas se répartissent selon les trois schémas des agrégats, des bases et des éléments, en prenant les cinq agrégats pour base ; les cinq agrégats, davantage condensés, ne sont que les deux dharmas de la forme et de l'esprit. Le « dharma-forme », au sens large, est le terme général pour l'existence matérielle, désignant tout ce qui a la nature de résistance\u2014c'est-à-dire ce qui occupe un espace défini, fait obstacle mutuel à soi et à autrui, et est sujet à la détérioration. Si l'on classe tous les dharmas selon les Cinq Catégories et Cent Dharmas, ils se divisent en dharmas-forme, dharmas-esprit, facteurs mentaux, dharmas non concomitants à l'esprit et dharmas inconditionnés. Parmi eux, le dharma-forme est appelé « agrégat de la forme » dans la classification des cinq agrégats, et le dharma-esprit « agrégat de la conscience ». Dans les Cinq Catégories de l'école, les dharmas-forme se divisent en trois classes et onze sortes : (1) les cinq facultés (œil, oreille, nez, langue, corps) ; (2) les cinq objets (forme, son, odeur, saveur, toucher) ; (3) la forme non manifestée. Au sein des Cinq Catégories, les dharmas-forme sont placés après les dharmas-esprit et les facteurs mentaux, car ils ne peuvent surgir de façon indépendante et ne sont que la manifestation de ces deux premiers.",
 'vi': "Đối lại với “tâm pháp”. Hết thảy các pháp chia làm ba khoa uẩn, xứ, giới, lấy năm uẩn làm cơ sở; năm uẩn quy nạp lại chỉ là hai pháp sắc và tâm. Cái gọi là sắc pháp, nói rộng, là tên gọi chung của tồn tại vật chất, chỉ chung vật có tính chất ngại, tức chiếm một không gian nhất định, có tính tự tha chướng ngại lẫn nhau và sẽ biến hoại. Nếu lấy “Ngũ vị bách pháp” phân loại vạn pháp, thì chia làm sắc pháp, tâm pháp, tâm sở pháp, tâm bất tương ưng hành pháp, vô vi pháp. Trong đó sắc pháp, theo cách phân năm uẩn gọi là sắc uẩn, tâm pháp gọi là thức uẩn. Trong Ngũ vị bách pháp của Duy Thức tông, sắc pháp chia ba loại mười một thứ: (1) năm căn nhãn, nhĩ, tỷ, thiệt, thân; (2) năm cảnh sắc, thanh, hương, vị, xúc; (3) vô biểu sắc. Trong Ngũ vị bách pháp, sắc pháp đứng sau tâm pháp và tâm sở pháp, là vì nó không thể độc lập sinh khởi, mà chỉ là biến hiện của hai loại trước.",
}

D['因缘'] = {
 'en': "A joint term for cause (hetu) and condition (pratyaya), and one of the four conditions established by the Consciousness-Only school. \u201cCause\u201d is the direct inner factor that gives rise to a result; \u201ccondition\u201d refers to the indirect factor of external assistance. Accordingly, \u201ccauses and conditions\u201d are also spoken of as inner cause and outer condition, or intimate cause and remote condition. Broadly, \u201ccause\u201d itself means cause-and-condition, including both inner cause and outer condition. All existents arise and cease through the gathering and dispersing of causes and conditions; this is called \u201carising from causes and conditions\u201d or \u201cdependent arising.\u201d Hence all dharmas that arise and cease through causes and conditions are called \u201cdharmas of conditioned arising and ceasing\u201d; and the result produced by the union of cause and condition is called the \u201cunion of causes and conditions.\u201d All existents provisionally arise through the union of causes and conditions and are without self-nature\u2014this is the principle of \u201cdependent arising, empty of nature.\u201d Taking afflictions as cause and karma as condition, one calls forth the fruit of the deluded realm; taking wisdom as cause and concentration as condition, one calls forth the fruit of the awakened realm. \u201cCause-condition\u201d (hetu-pratyaya) is also called the \u201cintimate cause-condition,\u201d the chief condition for the arising of any dharma\u2014in fact, the seeds within the eighth, ālaya, consciousness that can give rise to present-active resultant dharmas. Fascicle 7 of the Cheng weishi lun says: \u201cThe cause-condition means that conditioned dharmas intimately produce their own fruit; this has two aspects\u2014first, seeds; second, present activity.\u201d",
 'fr': "Terme conjoint pour cause (hetu) et condition (pratyaya), l'une des quatre conditions établies par l'école du Rien-que-conscience. La « cause » est le facteur interne direct qui donne naissance à un résultat ; la « condition » désigne le facteur indirect d'assistance externe. Ainsi, « causes et conditions » se dit aussi cause interne et condition externe, ou cause intime et condition lointaine. Au sens large, « cause » signifie cause-et-condition, incluant cause interne et condition externe. Tous les existants naissent et cessent par le rassemblement et la dispersion des causes et conditions ; c'est ce qu'on appelle « naître des causes et conditions » ou « production conditionnée ». D'où les « dharmas de la naissance-et-cessation conditionnée » ; et le résultat produit par l'union de la cause et de la condition est appelé « union des causes et conditions ». Tous les existants surgissent provisoirement par cette union et sont sans nature propre\u2014c'est le principe de la « coproduction conditionnée, vide de nature ». En prenant les afflictions pour cause et le karma pour condition, on appelle le fruit du domaine de l'illusion ; en prenant la sagesse pour cause et la concentration pour condition, on appelle le fruit du domaine de l'éveil. La « cause-condition » (hetu-pratyaya), dite aussi « cause-condition intime », est la condition principale de la naissance de tout dharma\u2014en fait les semences, au sein de la huitième conscience ālaya, capables de faire surgir les dharmas-fruits en activité présente. Le fascicule 7 du Cheng weishi lun dit : « La cause-condition signifie que les dharmas conditionnés produisent intimement leur propre fruit ; cela a deux aspects : premièrement les semences, deuxièmement l'activité présente. »",
 'vi': "Là tên gọi chung của nhân và duyên, một trong bốn duyên do Duy Thức tông lập. Nhân là nguyên nhân nội tại trực tiếp dẫn sinh kết quả; duyên chỉ nguyên nhân gián tiếp do bên ngoài trợ giúp. Theo đó, nhân duyên còn gọi là nội nhân ngoại duyên, thân nhân sơ duyên. Nói rộng, nhân tức nghĩa là nhân và duyên, bao gồm nội nhân và ngoại duyên. Hết thảy vạn hữu đều do nhân duyên tụ tán mà sinh diệt, gọi là nhân duyên sinh, duyên sinh, duyên khởi. Vì thế, hết thảy pháp do nhân duyên sinh diệt gọi là nhân duyên sinh diệt pháp; còn kết quả do nhân và duyên hòa hợp sinh ra gọi là nhân duyên hòa hợp. Hết thảy vạn hữu đều do nhân duyên hòa hợp giả sinh, không có tự tính, đó chính là lý “duyên khởi tính không”. Nếu lấy phiền não làm nhân, lấy nghiệp làm duyên, thì chiêu cảm quả cõi mê; lấy trí làm nhân, lấy định làm duyên, thì chiêu cảm quả cõi ngộ. Nhân duyên, còn gọi thân nhân duyên, là điều kiện chủ yếu cho hết thảy pháp sinh khởi, thật ra chính là chủng tử trong thức thứ tám a-lại-da có thể sinh khởi pháp quả hiện hành. Thành Duy Thức Luận quyển 7 nói: “Nhân duyên, là hữu vi pháp thân tự biện quả; thể này có hai: một là chủng tử, hai là hiện hành.”",
}

D['我空法有'] = {
 'en': "This means that the \u201cself\u201d is empty and void while \u201cdharmas\u201d are really existent. It is the position of the Hīnayāna Sarvāstivāda and similar schools. A sentient being's physical body is a provisional assemblage of the five aggregates and therefore has no permanent, unitary nature and no power of control\u2014this is the \u201cemptiness of self.\u201d Yet regarding all other existent dharmas, they held that these are not empty and void but really possess an independent essence, hence \u201cdharmas are existent.\u201d Conversely, if all other existent dharmas are likewise regarded as empty, this is called the \u201ctwofold emptiness of self and dharmas\u201d\u2014the position of Mahāyāna Buddhism.",
 'fr': "Cela signifie que le « soi » est vide et inexistant tandis que les « dharmas » sont réellement existants. C'est la position de l'école Hīnayāna Sarvāstivāda et de ses semblables. Le corps physique d'un être est un assemblage provisoire des cinq agrégats ; il n'a donc pas de nature permanente et unitaire ni de pouvoir de contrôle\u2014c'est la « vacuité du soi ». Mais quant à tous les autres dharmas existants, ils tenaient que ceux-ci ne sont pas vides mais possèdent réellement une essence indépendante, d'où « les dharmas sont existants ». Inversement, si tous les autres dharmas existants sont eux aussi tenus pour vides, cela s'appelle la « double vacuité du soi et des dharmas »\u2014la position du bouddhisme Mahāyāna.",
 'vi': "Chỉ việc “ngã” là không, còn “pháp” là thật có. Đây là chủ trương của Thuyết Nhất Thiết Hữu Bộ v.v. thuộc Tiểu thừa. Thân xác chúng sinh là do năm uẩn giả hợp mà thành, nên không có tính thường nhất, cũng không có năng lực chi phối, đó là “ngã không”. Nhưng đối với hết thảy pháp tồn tại khác, họ cho rằng chẳng phải là không, mà thật có bản chất độc lập của nó, nên nói “pháp hữu”. Ngược lại, nếu xem hết thảy pháp tồn tại khác cũng là không, thì gọi là “ngã pháp nhị không”, đó là chủ trương của Phật giáo Đại thừa.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_B2 →', len(D))
