#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['等流'] = {
 'en': "\u201cHomogeneous\u201d (deng) means \u201csame as\u201d; \u201coutflow\u201d (liu) means \u201cof the same class.\u201d \u201cHomogeneous outflow\u201d thus means \u201cof one and the same class\u201d\u2014simply put, when the fruit is of the same kind as its cause, it is called homogeneous outflow. Fascicle 21 of the Abhidharmakośa says: \u201cShamelessness, stinginess, and restlessness are the homogeneous outflow of greed\u201d\u2014meaning that shamelessness and the rest flow out from greed, since shamelessness and the like all possess a nature homogeneous with \u201cgreed,\u201d hence called homogeneous outflow.",
 'fr': "« Homogène » (deng) signifie « identique à » ; « écoulement » (liu) signifie « de la même classe ». L'« écoulement homogène » signifie donc « d'une seule et même classe »\u2014simplement dit, lorsque le fruit est de la même espèce que sa cause, on parle d'écoulement homogène. Le fascicule 21 de l'Abhidharmakośa dit : « L'impudeur, l'avarice et l'agitation sont l'écoulement homogène de la convoitise »\u2014c'est-à-dire que l'impudeur et le reste s'écoulent de la convoitise, puisque l'impudeur et les autres possèdent tous une nature homogène à la « convoitise », d'où le nom d'écoulement homogène.",
 'vi': "“Đẳng” nghĩa là đồng nhất; “lưu” nghĩa là lưu loại. Đẳng lưu, tức nghĩa cùng một lưu loại; nói đơn giản, quả đồng với nhân thì gọi là đẳng lưu. Câu-xá Luận quyển 21 chép: “Vô tàm, xan, trạo cử là đẳng lưu của tham”\u2014tức nói vô tàm v.v. là do tham lưu xuất, vì vô tàm v.v. đều là pháp có tính đồng với “tham”, nên gọi là đẳng lưu.",
}

D['菩提'] = {
 'en': "Sanskrit bodhi; rendered by meaning as awakening, wisdom, knowing, or way. Broadly, it is the wisdom that severs the afflictions of the world and accomplishes nirvāṇa\u2014the awakened wisdom that a Buddha, a pratyekabuddha, and a śrāvaka each attain at their respective fruit. Of these three kinds of bodhi, the Buddha's bodhi is supreme and ultimate, hence called anuttarā-samyak-saṃbodhi, translated as \u201cunsurpassed perfect and complete awakening,\u201d \u201cunsurpassed right and universal wisdom,\u201d \u201cunsurpassed right and true way,\u201d or \u201cunsurpassed enlightenment.\u201d Fascicle 4 of the Da zhidu lun says: \u201cBodhi is the name for the way of all Buddhas\u201d; fascicle 44 says: \u201cBodhi, in Chinese, is unsurpassed wisdom.\u201d This is the wisdom that clearly beholds the highest truth of dharma-nature\u2014suchness.",
 'fr': "Sanskrit bodhi ; rendu par éveil, sagesse, connaissance ou voie. Au sens large, c'est la sagesse qui tranche les afflictions du monde et accomplit le nirvāṇa\u2014la sagesse d'éveil qu'un Buddha, un pratyekabuddha et un śrāvaka atteignent chacun à leur fruit respectif. De ces trois sortes de bodhi, celle du Buddha est suprême et ultime, d'où le nom d'anuttarā-samyak-saṃbodhi, traduit par « éveil parfait et complet insurpassable », « sagesse droite et universelle insurpassable », « voie droite et vraie insurpassable » ou « éveil insurpassable ». Le fascicule 4 du Da zhidu lun dit : « Bodhi est le nom de la voie de tous les Buddhas » ; le fascicule 44 dit : « Bodhi, en chinois, est la sagesse insurpassable. » C'est la sagesse qui contemple clairement la vérité suprême de la nature-de-dharma\u2014l'ainsité.",
 'vi': "Phạn ngữ bodhi; dịch nghĩa là giác, trí, tri, đạo. Nói rộng, là trí tuệ đoạn tuyệt phiền não thế gian mà thành tựu niết-bàn\u2014tức giác trí mà Phật, Duyên Giác, Thanh Văn mỗi vị chứng được nơi quả của mình. Trong ba thứ bồ-đề ấy, bồ-đề của Phật là vô thượng rốt ráo, nên gọi là A-nậu-đa-la Tam-miệu Tam-bồ-đề, dịch là vô thượng chính đẳng chính giác, vô thượng chính biến trí, vô thượng chính chân đạo, vô thượng bồ-đề. Đại Trí Độ Luận quyển 4 nói: “Bồ-đề là danh xưng đạo của chư Phật”; quyển 44 nói: “Bồ-đề, tiếng Tần (Hán) là vô thượng trí tuệ.” Đây là trí tuệ chiếu thấy chân lý tối cao của pháp tính\u2014chân như.",
}

D['业力'] = {
 'en': "\u201cKarma\u201d means fabrication or action; the \u201cresidual force\u201d of such fabrication or action upon the future is called karmic force. Karma is further divided into wholesome and unwholesome; that wholesome and unwholesome karma have the power to give rise to fruits of pleasure and pain is itself proof of karmic force. All fruits of pleasure and pain are brought about by karmic force, hence the common saying, \u201cthe force of karma is inconceivable.\u201d",
 'fr': "« Karma » signifie fabrication ou action ; la « force résiduelle » de cette fabrication ou action sur l'avenir est appelée force karmique. Le karma se divise en salutaire et non-salutaire ; que le karma salutaire et non-salutaire ait le pouvoir de faire naître des fruits de plaisir et de douleur est en soi la preuve de la force karmique. Tous les fruits de plaisir et de douleur sont provoqués par la force karmique, d'où le dicton courant : « la force du karma est inconcevable ».",
 'vi': "Nghiệp là nghĩa tạo tác, hành vi; “dư thế” của sự tạo tác, hành vi ấy ảnh hưởng đến tương lai, gọi là nghiệp lực. Nghiệp lại có phân thiện, ác; nghiệp thiện ác có lực dụng sinh khởi quả khổ vui, cũng là chứng minh của nghiệp lực. Hết thảy quả khổ vui đều do nghiệp lực chiêu cảm, nên thường có câu “nghiệp lực bất khả tư nghì”.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_B5 →', len(D))
