#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['五根'] = {
 'en': "In \u201cfive faculties,\u201d faculty (indriya) means that which is able to produce, and also carries the sense of \u201cpredominance\u201d\u2014like the root of a plant, able to produce trunk, branch, flower, and fruit. The faculties are further divided into the subtle-form faculty and the coarse-dust (physical) faculty. The coarse faculty, also called the external faculty, is made of the coarse form of the four great elements: the eye, ear, nose, tongue, and body\u2014the five sense-organs mutually visible to us. But these external faculties have no capacity to give rise to consciousness; their function is to support the inner faculty, hence they are also called the \u201csupporting-dust\u201d faculty. The subtle-form faculty, also called the inner faculty or the faculty in the ultimate sense, is a transparent, pure kind of matter made of the subtle form of the four great elements. It is the locus where consciousness arises; in terms of modern scientific knowledge, these are the nerve fibers and nerve cells. A Buddhist verse describes the external faculties: \u201cThe eye is like a cluster of grapes, the ear like a rolled leaf, the nose like two hanging gourds, the tongue like a new crescent moon, the body like the head of a waist-drum.\u201d The Abhidharmakośa states: \u201cThe five faculties are the so-called eye, ear, nose, tongue, and body faculties.\u201d See the entry on the \u201cperceiving-portion.\u201d",
 'fr': "Dans « cinq facultés », faculté (indriya) désigne ce qui est capable de produire, et porte aussi le sens de « prédominance »\u2014comme la racine d'une plante, capable de produire tronc, branche, fleur et fruit. Les facultés se subdivisent en faculté de forme subtile et faculté de poussière grossière (physique). La faculté grossière, dite aussi faculté externe, est faite de la forme grossière des quatre grands éléments : l'œil, l'oreille, le nez, la langue, le corps\u2014les cinq organes des sens mutuellement visibles. Mais ces facultés externes n'ont pas le pouvoir de faire naître la conscience ; leur fonction est de soutenir la faculté interne, d'où le nom de faculté « poussière-support ». La faculté de forme subtile, dite aussi faculté interne ou faculté au sens ultime, est une matière transparente et pure, faite de la forme subtile des quatre grands éléments. C'est le lieu où naît la conscience ; en termes de science moderne, ce sont les fibres et cellules nerveuses. Une stance bouddhique décrit les facultés externes : « L'œil est comme une grappe de raisin, l'oreille comme une feuille enroulée, le nez comme deux courges pendantes, la langue comme un croissant de lune nouveau, le corps comme la tête d'un tambour de taille. » L'Abhidharmakośa dit : « Les cinq facultés sont les facultés dites de l'œil, de l'oreille, du nez, de la langue et du corps. » Voir l'entrée « portion percevante ».",
 'vi': "Trong “năm căn”, chữ căn (indriya) nghĩa là năng sinh, cũng có nghĩa tăng thượng, như rễ cây có thể sinh thân cành hoa quả. Căn lại chia làm tịnh sắc căn và phù trần căn. Phù trần căn còn gọi ngoại căn, do sắc thô của bốn đại tạo thành, tức là mắt, tai, mũi, lưỡi, thân\u2014năm cơ quan cảm giác mà ta thấy được lẫn nhau. Nhưng đây là căn ở ngoài, không có công năng sinh thức, tác dụng của nó là phù trợ nội căn, nên còn gọi phù căn trần. Tịnh sắc căn còn gọi nội căn, cũng gọi thắng nghĩa căn, là một thứ vật chất trong suốt, thanh tịnh, do tịnh sắc tứ đại tạo thành. Tịnh sắc căn là chỗ sinh thức; theo tri thức khoa học hiện đại mà xét, đó chính là sợi thần kinh và tế bào thần kinh. Trong sách Phật có bài kệ hình dung ngoại căn: “Mắt như chùm nho, tai như lá cuốn, mũi như hai quả bầu rủ xuống, lưỡi như vầng trăng non, thân như đầu trống lưng.” Câu-xá Luận chép: “Năm căn là gọi nhãn, nhĩ, tỷ, thiệt, thân căn.” Xem điều kiến phần.",
}

D['六波罗蜜'] = {
 'en': "Translated as the \u201csix perfections,\u201d meaning \u201creaching the far shore\u201d\u2014that is, accomplishing and completing the ideal. These are the six virtues that a bodhisattva in Mahāyāna Buddhism practices in order to attain Buddhahood: (1) The perfection of giving (dāna), of three kinds\u2014giving of wealth, of Dharma, and of fearlessness\u2014able to counteract stinginess and greed and to remove poverty. (2) The perfection of moral discipline (śīla): upholding the precepts and constantly self-examining, able to counteract evil karma and make body and mind cool and clear. (3) The perfection of patience (kṣānti): enduring persecution, able to counteract anger and settle the mind. (4) The perfection of vigor (vīrya): advancing without slackening or yielding when practicing the other five virtues, able to counteract indolence and grow wholesome dharmas. (5) The perfection of meditative concentration (dhyāna): cultivating meditation, able to counteract a scattered mind and settle it. (6) The perfection of wisdom (prajñā): able to counteract delusion and open true wisdom, thereby grasping the true meaning of life. These six perfections begin with giving and culminate in wisdom, from which one may know the magnanimous breadth of the Mahāyāna bodhisattva.",
 'fr': "Traduit par les « six perfections », signifiant « atteindre l'autre rive »\u2014c'est-à-dire accomplir et parfaire l'idéal. Ce sont les six vertus qu'un bodhisattva du bouddhisme Mahāyāna pratique pour atteindre la bouddhéité : (1) La perfection du don (dāna), de trois sortes\u2014don de biens, de Dharma, d'intrépidité\u2014capable de contrer l'avarice et la convoitise et d'éliminer la pauvreté. (2) La perfection de la discipline morale (śīla) : garder les préceptes et s'examiner constamment, capable de contrer le mauvais karma et de rendre le corps et l'esprit frais et clairs. (3) La perfection de la patience (kṣānti) : endurer la persécution, capable de contrer la colère et d'apaiser l'esprit. (4) La perfection de l'énergie (vīrya) : progresser sans relâche ni fléchissement en pratiquant les cinq autres vertus, capable de contrer la paresse et de faire croître les dharmas salutaires. (5) La perfection de la concentration (dhyāna) : cultiver le recueillement, capable de contrer l'esprit dispersé et de l'apaiser. (6) La perfection de la sagesse (prajñā) : capable de contrer l'ignorance et d'ouvrir la sagesse véritable, saisissant ainsi le sens véritable de la vie. Ces six perfections commencent par le don et culminent dans la sagesse, d'où l'on peut connaître la magnanimité du bodhisattva du Mahāyāna.",
 'vi': "Dịch là “sáu độ”, nghĩa là đến bờ kia\u2014tức nghĩa đạt thành, viên mãn lý tưởng. Đây là sáu đức mục mà Bồ Tát trong Phật giáo Đại thừa thực hành để thành Phật đạo: (1) Bố thí ba-la-mật, có ba thứ\u2014tài thí, pháp thí, vô úy thí\u2014hay đối trị xan tham, trừ nghèo khổ. (2) Trì giới ba-la-mật: giữ gìn giới luật và thường tự xét, hay đối trị ác nghiệp, khiến thân tâm mát mẻ. (3) Nhẫn nhục ba-la-mật: nhẫn chịu bức hại, hay đối trị sân hận, khiến tâm an trụ. (4) Tinh tấn ba-la-mật: khi thực hành năm đức mục kia, tiến lên không lười, không khuất, hay đối trị giải đãi, sinh trưởng thiện pháp. (5) Thiền định ba-la-mật: tu tập thiền định, hay đối trị loạn ý, khiến tâm an định. (6) Trí tuệ ba-la-mật (còn gọi Bát-nhã ba-la-mật): hay đối trị ngu si, mở trí tuệ chân thật, nắm được chân đế của sinh mệnh. Sáu ba-la-mật trên khởi từ bố thí, kết ở trí tuệ, do đó có thể biết được tấm lòng vĩ đại của Bồ Tát Đại thừa.",
}

D['六尘'] = {
 'en': "Refers to the dust of form, sound, smell, taste, touch, and dharmas\u2014in fact identical with the six objects (of the senses). See the entry \u201csix objects.\u201d",
 'fr': "Désigne la poussière de la forme, du son, de l'odeur, de la saveur, du toucher et des dharmas\u2014en fait identiques aux six objets (des sens). Voir l'entrée « six objets ».",
 'vi': "Chỉ sắc trần, thanh trần, hương trần, vị trần, xúc trần, pháp trần\u2014thật ra chính là sáu cảnh. Tham khảo điều lục cảnh.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_A3 合并后 defs_i18n.json 共', len(D), '条')
