#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['心法'] = {
 'en': "All dharmas in the universe may basically be divided into two great classes: form dharmas and mind dharmas. That which has the function of cognizing-and-apprehending is a mind dharma; that which lacks such function but has the function of resistance (materiality) is a form dharma. The \u201cmind dharmas\u201d referred to here are the first category among the Five Categories and Hundred Dharmas. There are eight mind dharmas\u2014the eye, ear, nose, tongue, body, mental, manas, and ālaya consciousnesses\u2014hence they are also called the \u201cmind-king dharmas\u201d or the \u201ceight ruling minds.\u201d",
 'fr': "Tous les dharmas de l'univers peuvent fondamentalement se répartir en deux grandes classes : les dharmas-forme et les dharmas-esprit. Ce qui a la fonction de connaître-et-appréhender est un dharma-esprit ; ce qui n'a pas cette fonction mais a la fonction de résistance (matérialité) est un dharma-forme. Les « dharmas-esprit » dont il est question ici sont la première catégorie parmi les Cinq Catégories et Cent Dharmas. Il y a huit dharmas-esprit\u2014les consciences de l'œil, de l'oreille, du nez, de la langue, du corps, la conscience mentale, le manas et l'ālaya\u2014d'où le nom de « dharmas esprit-roi » ou « huit esprits-rois ».",
 'vi': "Hết thảy pháp trong vũ trụ về cơ bản có thể chia làm hai loại lớn: sắc pháp và tâm pháp. Cái có tác dụng duyên lự là tâm pháp; cái không có tác dụng duyên lự mà có tác dụng chất ngại là sắc pháp. Tâm pháp nói ở đây là vị pháp thứ nhất trong Ngũ vị bách pháp. Tâm pháp có tám, tức nhãn, nhĩ, tỷ, thiệt, thân, ý, mạt-na, a-lại-da tám thức, nên còn gọi là “tâm vương pháp”, hay “tám tâm vương”.",
}

D['生死'] = {
 'en': "Means that, on the basis of karmic causes, beings undergo an unending succession of births and deaths within the six deluded destinies\u2014gods, humans, asuras, hungry ghosts, animals, and hells. It is set in contrast to nirvāṇa. Because birth-and-death is endless, it is likened to an ocean and called the \u201cocean of birth-and-death\u201d; because it is a world of suffering, it is also called the \u201cbitter sea of birth-and-death.\u201d To cross this bitter sea and reach the far shore of nirvāṇa is extremely difficult, hence it is also called the \u201cocean hard to cross.\u201d Fascicle 8 of the Cheng weishi lun sets out two kinds of birth-and-death: (1) Segmented birth-and-death: with contaminated good and evil karma as cause and the hindrance of afflictions as condition, one receives a coarse retribution within the three realms; the lifespan and bodily size of this retribution are fixed within limits, hence it is called the \u201csegmented body,\u201d and to transmigrate receiving such a body is segmented birth-and-death. (2) Transformational birth-and-death (also \u201cinconceivable transformational birth-and-death\u201d): arhats, pratyekabuddhas, and bodhisattvas of great power, though no longer subject to segmented birth-and-death, take uncontaminated discriminating karma as cause and the hindrance to the knowable as condition, and receive a superior, subtle retribution-body beyond the three realms\u2014the \u201cmind-made body\u201d\u2014with which they re-enter the three realms to cultivate the bodhisattva practice up to Buddhahood. Because of the power of their compassionate vows, the lifespan and body of this received form can be freely transformed and altered without fixed limit, hence it is called the \u201ctransformational body,\u201d and receiving such a body is transformational birth-and-death. In addition, the Xianshi lun speaks of four kinds of birth-and-death and the Mohe zhiguan of seven kinds, here omitted.",
 'fr': "Signifie que, sur la base de causes karmiques, les êtres subissent une succession sans fin de naissances et de morts au sein des six destinées d'illusion\u2014dieux, humains, asuras, esprits affamés, animaux et enfers. Cela s'oppose au nirvāṇa. Parce que le cycle est sans fin, on le compare à un océan, l'« océan des naissances et des morts » ; parce que c'est un monde de souffrance, on l'appelle aussi la « mer amère des naissances et des morts ». Traverser cette mer amère pour atteindre l'autre rive du nirvāṇa est extrêmement difficile, d'où le nom d'« océan difficile à franchir ». Le fascicule 8 du Cheng weishi lun expose deux sortes de naissance-et-mort : (1) La naissance-et-mort segmentée : ayant pour cause le karma bon et mauvais contaminé et pour condition l'obstacle des afflictions, on reçoit une rétribution grossière dans les trois mondes ; la durée de vie et la taille corporelle en sont fixées dans des limites, d'où le nom de « corps segmenté ». (2) La naissance-et-mort transformationnelle (ou « inconcevable ») : arhats, pratyekabuddhas et bodhisattvas de grande puissance, bien que non soumis à la naissance-et-mort segmentée, prennent pour cause le karma discriminant non contaminé et pour condition l'obstacle au connaissable, et reçoivent hors des trois mondes un corps de rétribution supérieur et subtil\u2014le « corps issu du mental »\u2014avec lequel ils rentrent dans les trois mondes pour cultiver la pratique du bodhisattva jusqu'à la bouddhéité. Par la force de leurs vœux de compassion, la durée de vie et le corps ainsi reçus peuvent se transformer librement sans limite fixe, d'où le nom de « corps transformationnel ». En outre, le Xianshi lun parle de quatre sortes et le Mohe zhiguan de sept sortes de naissance-et-mort, ici omises.",
 'vi': "Nghĩa là nương nơi nghiệp nhân mà trong sáu đường mê (trời, người, a-tu-la, ngạ quỷ, súc sinh, địa ngục) sinh tử nối nhau mãi không cùng tận. Đối lại với “niết-bàn”. Lại vì sinh tử vô tận, lấy biển làm ví dụ, nên gọi là biển sinh tử; sinh tử là thế giới khổ não, nên cũng gọi là biển khổ sinh tử; vượt biển khổ sinh tử mà đến bờ kia niết-bàn, việc ấy rất khó, nên còn gọi là biển khó vượt. Thành Duy Thức Luận quyển 8 nêu hai loại sinh tử: (1) Phần đoạn sinh tử: lấy nghiệp thiện ác hữu lậu làm nhân, phiền não chướng làm duyên, thọ quả báo thô trong ba cõi; quả báo ấy có hạn định nhất định về tuổi thọ dài ngắn, thân thể lớn nhỏ, nên gọi là phần đoạn thân; thọ thân phần đoạn mà luân hồi gọi là phần đoạn sinh tử. (2) Biến dịch sinh tử (còn gọi bất tư nghì biến dịch sinh tử): A-la-hán, Bích-chi-phật, đại lực Bồ Tát tuy không còn luân hồi phần đoạn sinh tử, nhưng lấy nghiệp hữu phân biệt vô lậu làm nhân, sở tri chướng làm duyên, ở ngoài ba cõi thọ thân quả báo thù thắng vi diệu, tức thọ ý sinh thân, rồi lấy thân này vào lại ba cõi tu Bồ Tát hạnh cho đến thành Phật quả. Thân ấy do sức bi nguyện nên tuổi thọ, thân thể đều có thể tự do biến đổi, không có hạn định nhất định, nên gọi là biến dịch thân; thọ thân biến dịch gọi là biến dịch sinh tử. Ngoài ra, Hiển Thức Luận có thuyết bốn loại sinh tử, Ma-ha Chỉ Quán có thuyết bảy loại sinh tử, ở đây lược qua.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_A4 合并后 defs_i18n.json 共', len(D), '条')
