#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['大乘百法明门论'] = {
 'en': "In one fascicle; composed by the treatise-master Vasubandhu, translated by the Tang Tripiṭaka-master Xuanzang. It is one of the \u201cone root and ten branch\u201d texts of the Consciousness-Only school\u2014also called the \u201cbranch that briefly sets out names and numbers\u201d\u2014taking \u201call dharmas are without self\u201d as its tenet. The treatise draws the enumeration of the hundred dharmas from the \u201cFundamental Stage\u201d chapter of the Yogācārabhūmi-śāstra, and is one of the important texts on which the Consciousness-Only school relies. The whole work briefly divides all dharmas into the Five Categories and Hundred Dharmas: (1) mind-king dharmas, the eight consciousnesses; (2) mental-factor dharmas, six divisions such as the universally active, comprising fifty-one factors; (3) form dharmas, eleven kinds such as the eye; (4) dharmas not concomitant with mind, twenty-four kinds such as \u201cattainment\u201d; (5) unconditioned dharmas, six kinds such as unconditioned space.",
 'fr': "En un fascicule ; composé par le maître Vasubandhu, traduit par le maître du Tripiṭaka Xuanzang, sous les Tang. C'est l'un des textes « une racine et dix branches » de l'école du Rien-que-conscience\u2014aussi appelé « branche exposant brièvement noms et nombres »\u2014prenant pour thèse « tous les dharmas sont sans soi ». Le traité tire l'énumération des cent dharmas du chapitre « Stade fondamental » du Yogācārabhūmi-śāstra ; c'est l'un des textes importants sur lesquels s'appuie l'école. L'ouvrage répartit brièvement tous les dharmas en Cinq Catégories et Cent Dharmas : (1) les dharmas esprit-roi, les huit consciences ; (2) les dharmas facteurs mentaux, six divisions telles que les universellement actifs, soit cinquante et un facteurs ; (3) les dharmas-forme, onze sortes telles que l'œil ; (4) les dharmas non concomitants à l'esprit, vingt-quatre sortes telles que l'« obtention » ; (5) les dharmas inconditionnés, six sortes telles que l'espace inconditionné.",
 'vi': "Gồm một quyển; do luận sư Thế Thân (Vasubandhu) tạo, Tam Tạng Huyền Trang đời Đường dịch. Là một trong “một gốc mười nhánh” của Duy Thức tông, còn gọi là “lược trần danh số chi”, lấy “nhất thiết pháp vô ngã” làm tông. Bộ luận này trích danh số bách pháp từ phẩm “Bản Địa Phần” trong Du Già Sư Địa Luận, là một trong những bộ luận quan trọng mà Duy Thức tông y cứ. Toàn sách lược chia các pháp thành Ngũ vị bách pháp: (1) tâm vương pháp, tám thức; (2) tâm sở hữu pháp, sáu vị như biến hành, gồm năm mươi mốt tâm sở; (3) sắc pháp, mười một thứ như nhãn; (4) tâm bất tương ưng hành pháp, hai mươi bốn thứ như “đắc”; (5) vô vi pháp, sáu thứ như hư không vô vi.",
}

D['大乘庄严经论'] = {
 'en': "Composed by Asaṅga, translated by Prabhākaramitra in the Tang dynasty; in thirteen fascicles. Its content expounds the bodhisattva's arousing of the aspiration, his practice, and the various methods he should cultivate. Also called the Treatise on the Ornament of the Mahāyāna; the whole work is divided into twenty-four chapters. According to fascicle 1 of the Lamp of the Definitive Meaning of the Cheng weishi lun and fascicle 4 of the Commentary on the Cheng weishi lun, the root verses were composed by the bodhisattva Maitreya, while the prose commentary was composed by the bodhisattva Vasubandhu.",
 'fr': "Composé par Asaṅga, traduit par Prabhākaramitra sous les Tang ; en treize fascicules. Son contenu expose la production de l'esprit d'éveil par le bodhisattva, sa pratique et les diverses méthodes qu'il doit cultiver. Aussi appelé Traité de l'Ornement du Mahāyāna ; l'ouvrage est divisé en vingt-quatre chapitres. Selon le fascicule 1 de la Lampe du sens définitif du Cheng weishi lun et le fascicule 4 du Commentaire du Cheng weishi lun, les stances-racines furent composées par le bodhisattva Maitreya, tandis que le commentaire en prose le fut par le bodhisattva Vasubandhu.",
 'vi': "Do Vô Trước (Asaṅga) tạo, Ba-la-phả-mật-đa-la dịch đời Đường; gồm mười ba quyển. Nội dung giải thích việc Bồ Tát phát tâm, tu hành và các pháp môn nên tu tập. Còn gọi là Đại Thừa Trang Nghiêm Luận; toàn sách chia thành hai mươi bốn phẩm. Theo quyển 1 Thành Duy Thức Luận Liễu Nghĩa Đăng và quyển 4 Thành Duy Thức Luận Thuật Ký, thì bổn tụng do Bồ Tát Từ Thị Di-lặc tạo, còn phần thích luận do Bồ Tát Thiên Thân tạo.",
}

D['五位百法'] = {
 'en': "One of the classifications of dharmas. The Abhidharmakośa school posits Five Categories and Seventy-five Dharmas, whereas the Consciousness-Only school divides all dharmas into Five Categories and One Hundred Dharmas: (1) Mind-king dharmas, also called the eight ruling minds: the six consciousnesses (eye, ear, nose, tongue, body, mental), plus the seventh manas and the eighth ālaya\u2014eight in all. (2) Mental-factor dharmas: fifty-one factors, in six divisions\u2014universally active, object-specific, wholesome, afflictive, secondary afflictive, and indeterminate. (3) Form dharmas: the five faculties (eye, ear, nose, tongue, body), the five objects (form, sound, smell, taste, touch), and the \u201cform included in the dharma-base\u201d that is the object of mental consciousness\u2014eleven in all. (4) Dharmas not concomitant with mind: twenty-four kinds such as attainment, life-faculty, generic likeness, the nature of dissimilar arising, the concentration of no-thought, the concentration of cessation, the retribution of no-thought, name-groups, phrase-groups, syllable-groups, arising, aging, abiding, impermanence, flowing-turning, definite distinction, correspondence, speed, sequence, place, time, number, the state of union, and the state of non-union. (5) Unconditioned dharmas: six kinds\u2014space, cessation through discrimination, cessation not through discrimination, the cessation of the unmoving, the cessation of perception-and-feeling, and suchness. Of these five classes, all but the unconditioned dharmas belong to the conditioned. See the Treatise on the Hundred Dharmas.",
 'fr': "L'une des classifications des dharmas. L'école de l'Abhidharmakośa pose Cinq Catégories et Soixante-quinze Dharmas, tandis que l'école du Rien-que-conscience répartit tous les dharmas en Cinq Catégories et Cent Dharmas : (1) Dharmas esprit-roi, aussi appelés les huit esprits-rois : les six consciences (œil, oreille, nez, langue, corps, mental), plus la septième (manas) et la huitième (ālaya)\u2014huit en tout. (2) Dharmas facteurs mentaux : cinquante et un facteurs, en six divisions\u2014universellement actifs, spécifiques à l'objet, salutaires, afflictifs, afflictifs secondaires, indéterminés. (3) Dharmas-forme : les cinq facultés (œil, oreille, nez, langue, corps), les cinq objets (forme, son, odeur, saveur, toucher) et la « forme incluse dans la base des dharmas », objet de la conscience mentale\u2014onze en tout. (4) Dharmas non concomitants à l'esprit : vingt-quatre sortes telles que l'obtention, la faculté vitale, la similitude générique, la nature de naissance dissemblable, la concentration sans pensée, la concentration de cessation, la rétribution sans pensée, les groupes de noms, de phrases, de syllabes, la naissance, la vieillesse, la durée, l'impermanence, le flux, la distinction définie, la correspondance, la vitesse, la succession, le lieu, le temps, le nombre, l'état d'union et de non-union. (5) Dharmas inconditionnés : six sortes\u2014l'espace, la cessation par discrimination, la cessation sans discrimination, la cessation de l'immobile, la cessation de la perception-et-sensation, et l'ainsité. De ces cinq classes, toutes sauf les dharmas inconditionnés relèvent du conditionné. Voir le Traité des Cent Dharmas.",
 'vi': "Một trong các cách phân loại các pháp. Câu-xá tông lập Ngũ vị thất thập ngũ pháp, còn Duy Thức tông chia hết thảy pháp thành Ngũ vị bách pháp: (1) Tâm vương pháp, còn gọi tám tâm vương: sáu thức (nhãn, nhĩ, tỷ, thiệt, thân, ý), thêm thức thứ bảy mạt-na và thức thứ tám a-lại-da, cộng tám thứ. (2) Tâm sở hữu pháp: năm mươi mốt tâm sở, chia sáu vị\u2014biến hành, biệt cảnh, thiện, phiền não, tùy phiền não, bất định. (3) Sắc pháp: năm căn (nhãn, nhĩ, tỷ, thiệt, thân), năm cảnh (sắc, thanh, hương, vị, xúc), và pháp xứ sở nhiếp sắc mà ý thức đối, cộng mười một thứ. (4) Tâm bất tương ưng hành pháp: hai mươi bốn thứ như đắc, mạng căn, chúng đồng phần, dị sinh tính, vô tưởng định, diệt tận định, vô tưởng báo, danh thân, cú thân, văn thân, sinh, lão, trụ, vô thường, lưu chuyển, định dị, tương ưng, thế tốc, thứ đệ, phương, thời, số, hòa hợp tính, bất hòa hợp tính. (5) Vô vi pháp: sáu thứ\u2014hư không, trạch diệt, phi trạch diệt, bất động diệt, tưởng thọ diệt, chân như. Trong năm loại ấy, trừ vô vi pháp, bốn loại còn lại thuộc hữu vi. Xem Bách Pháp Minh Môn Luận.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_A2 合并后 defs_i18n.json 共', len(D), '条')
