#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['外道'] = {
 'en': "Refers to all religions other than Buddhism. In ancient India, Buddhism regarded \u201couter-path\u201d practitioners as holy recluses worthy of respect, the term meaning \u201cthose who teach correctly\u201d or \u201cascetics\u201d; correspondingly Buddhism called itself the \u201cinner path,\u201d its scriptures the \u201cinner canon,\u201d and non-Buddhist scriptures the \u201couter canon.\u201d In later ages the term gradually took on the sense of deviant views and false doctrines, and \u201couter-path\u201d became a contemptuous, dismissive epithet meaning one whose false teaching lies outside the truth. The kinds of outer paths are very many\u2014e.g., the six heterodox masters, the six ascetic outer paths, the sixteen outer paths, the twenty outer paths, the sixty-two views, the ninety-six kinds of outer paths, and so forth.",
 'fr': "Désigne toutes les religions autres que le bouddhisme. Dans l'Inde ancienne, le bouddhisme considérait les tenants des « voies extérieures » comme de saints reclus dignes de respect, le terme signifiant « ceux qui enseignent correctement » ou « ascètes » ; par contraste, le bouddhisme se nommait la « voie intérieure », ses écritures le « canon intérieur », et les écritures non bouddhiques le « canon extérieur ». Aux âges ultérieurs, le terme prit peu à peu le sens de vues déviantes et de fausses doctrines, et « voie extérieure » devint une épithète méprisante désignant celui dont la fausse doctrine se situe hors de la vérité. Les sortes de voies extérieures sont très nombreuses\u2014par ex. les six maîtres hétérodoxes, les six voies ascétiques, les seize, les vingt voies extérieures, les soixante-deux vues, les quatre-vingt-seize sortes de voies extérieures, etc.",
 'vi': "Chỉ hết thảy tôn giáo ngoài Phật giáo. Thời cổ Ấn Độ, Phật giáo xem ngoại đạo là bậc ẩn dật thần thánh đáng tôn kính, nghĩa là bậc chính thuyết, bậc khổ hạnh; đối lại, Phật giáo tự xưng là nội đạo, kinh điển Phật giáo tự xưng là nội điển, gọi kinh điển ngoài Phật giáo là ngoại điển. Đến đời sau, dần dần thêm nghĩa dị kiến, tà thuyết, ngoại đạo bèn thành lời khinh miệt bài xích, nghĩa là kẻ theo tà pháp ngoài chân lý. Chủng loại ngoại đạo rất nhiều, như lục sư ngoại đạo, sáu khổ hạnh ngoại đạo, mười sáu ngoại đạo, hai mươi ngoại đạo, sáu mươi hai kiến, chín mươi sáu thứ ngoại đạo v.v.",
}

D['有为法'] = {
 'en': "\u201cActive/made\u201d (wei) means having something done or fabricated. Abbreviated \u201cconditioned.\u201d It broadly refers to phenomena produced by the coming-together of causes and conditions; narrowly, it points specifically to human fabricating activity. That is, all phenomena that stand in mutual relation and in the flux of arising-and-ceasing, characterized by the four conditioned marks of arising, abiding, changing, and ceasing. In contrast, that which is forever unchanging and absolutely existent is called the unconditioned. According to fascicle 5 of the Jushe lun guangji, the fabricating of causes and conditions is called \u201cactivity\u201d; form, mind, and other dharmas arise from causes and conditions and have such causal fabrication, hence are called \u201cconditioned\u201d\u2014so \u201cconditioned\u201d is also another name for dependently arisen dharmas. The Dasheng yizhang says: \u201c\u2018Active\u2019 has the sense of aggregating, arising, and fabricating; because dharmas have such activity, they are called conditioned.\u201d",
 'fr': "« Actif/fait » (wei) signifie qu'il y a quelque chose de fait ou de fabriqué. Abrégé en « conditionné ». Il désigne largement les phénomènes produits par la réunion des causes et conditions ; au sens étroit, il vise spécifiquement l'activité fabricatrice humaine. C'est-à-dire tous les phénomènes en relation mutuelle et dans le flux du naître-et-cesser, caractérisés par les quatre marques du conditionné : naissance, durée, changement et cessation. À l'opposé, ce qui est à jamais immuable et absolument existant est appelé l'inconditionné. Selon le fascicule 5 du Jushe lun guangji, la fabrication par causes et conditions est dite « activité » ; la forme, l'esprit et les autres dharmas naissent des causes et conditions et ont cette fabrication causale, d'où le nom de « conditionné »\u2014ainsi « conditionné » est aussi un autre nom des dharmas issus de la coproduction conditionnée. Le Dasheng yizhang dit : « « Actif » a le sens d'agréger, de surgir et de fabriquer ; parce que les dharmas ont cette activité, on les nomme conditionnés. »",
 'vi': "“Vi” nghĩa là có tạo tác, tác động. Còn gọi tắt là hữu vi. Chỉ chung các hiện tượng do nhân duyên hòa hợp tạo ra; nghĩa hẹp, đặc chỉ hành vi tạo tác của con người. Tức hết thảy hiện tượng ở trong mối liên hệ hỗ tương, trong sinh diệt biến hóa, lấy bốn tướng hữu vi\u2014sinh, trụ, dị, diệt\u2014làm đặc trưng. Đối lại, cái vĩnh viễn bất biến và tuyệt đối tồn tại thì gọi là vô vi pháp. Theo Câu-xá Luận Quang Ký quyển 5, nhân duyên tạo tác gọi là “vi”; sắc, tâm v.v. từ nhân duyên sinh, có sự tạo tác của nhân duyên, nên gọi là hữu vi\u2014vì thế hữu vi cũng là tên khác của duyên khởi pháp. Đại Thừa Nghĩa Chương nói: “‘Vi’ là nghĩa tập khởi tạo tác; pháp vì có sự tạo tác nên gọi là hữu vi.”",
}

D['自性'] = {
 'en': "Refers to the intrinsic nature of a thing's own essence; the Consciousness-Only masters mostly call it the \u201cown-mark.\u201d That is, the truly unchanging, pure and unmixed individual character that each dharma possesses is called its self-nature. In other words, self-nature is the essence of a dharma\u2014that which is originally so, forever so, and cannot be altered by any means. In fact, all dharmas are without self-nature; only because they are without self-nature can they be malleable, and only so can there be arising, ceasing, and transformation. The Madhyamaka school holds that all dharmas are formed by the coming-together of causes and conditions and have no fixed self-nature, hence self-nature is empty. Thus the Madhyamaka theory of \u201cdependent arising, empty of nature\u201d is built upon the foundation that all dharmas are without self-nature.",
 'fr': "Désigne la nature intrinsèque de l'essence propre d'une chose ; les maîtres du Rien-que-conscience l'appellent le plus souvent la « marque propre ». C'est-à-dire le caractère individuel véritablement immuable, pur et sans mélange que possède chaque dharma : on l'appelle sa nature propre. Autrement dit, la nature propre est l'essence d'un dharma\u2014ce qui est originellement ainsi, toujours ainsi, et ne peut être altéré par aucun moyen. En réalité, tous les dharmas sont sans nature propre ; c'est précisément parce qu'ils en sont dépourvus qu'ils sont malléables, et qu'il peut y avoir naissance, cessation et transformation. L'école Madhyamaka soutient que tous les dharmas sont formés par la réunion des causes et conditions et n'ont pas de nature propre fixe, d'où la vacuité de la nature propre. Ainsi la théorie Madhyamaka de la « coproduction conditionnée, vide de nature » repose sur le fondement que tous les dharmas sont sans nature propre.",
 'vi': "Chỉ bản tính của tự thể; các nhà Duy Thức phần nhiều gọi là tự tướng. Tức cá tính chân thật bất biến, thuần khiết không tạp mà mỗi pháp tự có, gọi là tự tính. Nói cách khác, tự tính chính là bản chất của hết thảy pháp, tức cái vốn như vậy, mãi mãi như vậy, không thể dùng bất cứ cách nào làm cho biến đổi. Thật ra, hết thảy pháp đều vô tự tính; vô tự tính mới có tính khả biến, mới có sinh diệt biến dịch. Học phái Trung Quán cho rằng các pháp đều do nhân duyên hòa hợp mà thành, không có tự tính nhất định, nên tự tính tức không. Vì thế lý thuyết “duyên khởi tính không” của Trung Quán được xây dựng trên nền tảng hết thảy pháp vô tự tính.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('batch_B1 →', len(D))
