#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""核心短中条：先手写入库，不等长文批。"""
import json, os
BASE = os.path.dirname(__file__)
p = os.path.join(BASE, 'defs_i18n.json')
D = json.load(open(p, encoding='utf-8'))

D['末那识'] = {
'en': "Sanskrit manas, rendered “mind,” with the sense of deliberation. It is the seventh of the eight ruling minds in Consciousness-Only. The Extensive Mahāyāna Treatise on the Five Aggregates says it takes the storehouse-consciousness as its object, and constantly corresponds with self-delusion, self-view, self-conceit, and self-love, continuing of one class without interruption—except in arhatship, the noble path, and the concentration of cessation. The manas constantly grasps the perceiving-portion of the eighth, ālaya, as a “self,” and deliberates on it with constant scrutiny. It is the faculty on which the sixth, mental, consciousness depends; of obscuring-neutral nature; and the root of grasping at a self. When deluded it creates evil karma; when purified it severs afflictions and realizes the twofold emptiness of persons and dharmas—hence also called the defiled-and-pure consciousness, the deliberating consciousness, or the deliberating transforming consciousness. See Cheng weishi lun, fascicle 4.",
'fr': "Sanskrit manas, rendu « mental », au sens de délibération. C'est le septième des huit esprits-rois dans le Rien-que-conscience. Le Traité étendu du Mahāyāna sur les Cinq Agrégats dit qu'il prend la conscience-réceptacle pour objet et correspond constamment à l'ignorance-de-soi, la vue-de-soi, l'orgueil-de-soi et l'amour-de-soi, se poursuivant sans interruption—sauf chez l'arhat, sur la voie noble et dans la concentration de cessation. Le manas saisit constamment la portion percevante de la huitième conscience ālaya comme un « soi » et délibère sur elle avec un examen constant. Il est la faculté dont dépend la sixième conscience mentale ; de nature neutre-obscurcissante ; et la racine de la saisie d'un soi. Égaré, il crée le mauvais karma ; purifié, il tranche les afflictions et réalise la double vacuité des personnes et des dharmas—d'où aussi le nom de conscience souillée-et-pure, conscience délibérante, ou conscience transformante délibérante. Voir Cheng weishi lun, fasc. 4.",
'vi': "Phạn ngữ manas, dịch nghĩa là ý, nghĩa tư lương. Là thức thứ bảy trong tám tâm vương của Duy Thức tông. Đại Thừa Quảng Ngũ Uẩn Luận nói: thức này duyên tàng thức làm cảnh, hằng tương ưng với ngã si, ngã kiến, ngã mạn, ngã ái, trước sau một loại tương tục tùy chuyển—trừ địa vị A-la-hán, thánh đạo, diệt định hiện tiền. Mạt-na hằng chấp kiến phần của thức thứ tám a-lại-da làm “ngã” mà “hằng thẩm tư lương”. Mạt-na là căn mà ý thức thứ sáu nương tựa; tính chất hữu phú vô ký; lại là căn bản của ngã chấp. Nếu chấp mê vọng thì tạo ác nghiệp; ngược lại thì đoạn diệt phiền não ác nghiệp, triệt ngộ chân lý nhân pháp nhị không—nên gọi nhiễm tịnh thức, cũng gọi tư lương thức, tư lương năng biến thức. Xem Thành Duy Thức Luận quyển 4.",
}

D['见分'] = {
'en': "One of the four portions of the substance of consciousness. The perceiving portion is the cognitive (able-to-cognize) function of the consciousnesses—the subject that knows things, illuminating the object (the image portion). “Seeing” means illuminating and the mind's clarity. When consciousness arises, from its own substance it manifests the image and perceiving portions: the image portion is form-dharma; the perceiving portion is mind-dharma. Both are manifestations of the consciousness-substance; bringing objects back to mind establishes consciousness-only.",
'fr': "L'une des quatre portions de la substance de la conscience. La portion percevante est la fonction cognitive (capable de connaître) des consciences—le sujet qui connaît les choses, illuminant l'objet (la portion-image). « Voir » signifie illuminer et la clarté de l'esprit. Quand la conscience surgit, de sa propre substance elle manifeste les portions image et percevante : la portion-image est dharma-forme ; la portion percevante est dharma-esprit. Toutes deux sont des manifestations de la substance-conscience ; ramener les objets à l'esprit établit le rien-que-conscience.",
'vi': "Một trong bốn phần của thức thể. Kiến phần chỉ tác dụng năng duyên của các thức, là chủ thể nhận thức sự vật, hay chiếu biết cảnh sở duyên (tướng phần). “Kiến” tức kiến chiếu, tâm tính sáng rõ. Tâm thức sinh khởi, từ tự thể biến hiện tướng, kiến hai phần: tướng phần là sắc pháp, kiến phần là tâm pháp; cả hai đều do thức thể biến hiện, nhiếp vật quy tâm, nên thành duy thức.",
}

D['相分'] = {
'en': "One of the four portions. The image portion is the objective appearance manifested on the mind's own substance and cognized by the perceiving portion—encompassing all so-called objective phenomena. When consciousness arises it manifests image and perceiving portions: perceiving is able-to-cognize; image is the cognized appearance. The image is the appearance manifested from the form-seeds of the eighth consciousness; it is not the “essential form” of an external object, but an image re-manifested on the eye-consciousness in dependence on the eighth's image-form, which the eye-consciousness's perceiving portion then cognizes. Hence: “What consciousness cognizes is only what consciousness manifests.”",
'fr': "L'une des quatre portions. La portion-image est l'apparence objective manifestée sur la substance propre de l'esprit et connue par la portion percevante—englobant tous les phénomènes dits objectifs. Quand la conscience surgit, elle manifeste image et percevant : le percevant est capable de connaître ; l'image est l'apparence connue. L'image est l'apparence manifestée à partir des semences-forme de la huitième conscience ; ce n'est pas la « forme essentielle » d'un objet externe, mais une image re-manifestée sur la conscience visuelle en dépendance de la forme-image de la huitième, que la portion percevante de la conscience visuelle connaît ensuite. D'où : « Ce que la conscience connaît n'est que ce que la conscience manifeste. »",
'vi': "Một trong bốn phần tâm pháp. Tướng phần là cảnh tướng do tự tâm thể biến hiện để kiến phần duyên—thâu nhiếp hết thảy hiện tượng gọi là khách quan. Tâm thức sinh khởi biến hiện tướng, kiến hai phần: kiến phần là năng duyên, tướng phần là cảnh tướng sở duyên. Tướng phần là cảnh tướng do chủng tử sắc pháp của thức thứ tám biến hiện; ảnh tượng chẳng phải “bản chất sắc” của ngoại cảnh, mà nương tướng phần sắc của thức thứ tám, trên nhãn thức lại biến hiện một lớp ảnh tượng, do kiến phần của nhãn thức đi duyên. Nên nói: “Thức sở duyên, duy thức sở biến.”",
}

D['自证分'] = {
'en': "Also called the self-portion; the third of the four portions. The perceiving portion can cognize and discern the image portion but cannot know by itself whether its seeing is erroneous; hence another function that verifies the perceiving portion is required—the self-aware portion. It is the very substance of consciousness. The self-aware and re-aware portions verify each other.",
'fr': "Aussi appelée portion-substance ; la troisième des quatre portions. La portion percevante peut connaître et discerner la portion-image mais ne peut savoir d'elle-même si sa vision est erronée ; d'où la nécessité d'une autre fonction qui vérifie la portion percevante—la portion d'auto-connaissance. Elle est la substance même de la conscience. Les portions d'auto-connaissance et de ré-connaissance se vérifient mutuellement.",
'vi': "Còn gọi tự thể phần; phần thứ ba trong thức thể tứ phần. Kiến phần có tác dụng duyên lự, liễu biệt tướng phần, nhưng không tự biết cái thấy của mình có sai lầm hay không, nên phải có thêm tác dụng chứng biết kiến phần—tức tự chứng phần. Tự chứng phần chính là tự thể của thức. Tự chứng phần và chứng tự chứng phần hỗ chứng lẫn nhau.",
}

D['证自证分'] = {
'en': "The fourth of the four portions: the function that again verifies the self-aware portion. The self-aware portion verifies the perceiving portion; the re-aware portion verifies the self-aware portion; and the re-aware portion is in turn verified by the self-aware portion—the two cognize and verify each other, so a fifth portion need not be set up.",
'fr': "La quatrième des quatre portions : la fonction qui vérifie à nouveau la portion d'auto-connaissance. Celle-ci vérifie la portion percevante ; la portion de ré-connaissance vérifie l'auto-connaissance ; et la ré-connaissance est à son tour vérifiée par l'auto-connaissance—les deux se connaissent et se vérifient mutuellement, sans qu'il faille poser une cinquième portion.",
'vi': "Phần thứ tư trong thức thể tứ phần: tác dụng chứng biết lại tự chứng phần. Tự chứng phần chứng biết kiến phần; chứng tự chứng phần chứng biết tự chứng phần; còn chứng tự chứng phần lại do tự chứng phần chứng biết—hai cái hỗ duyên hỗ chứng, nên không cần lập phần thứ năm.",
}

D['识体四分'] = {
'en': "A Consciousness-Only doctrine: the cognitive function of mind-consciousness has four divisions, arising in the transformation of consciousness—(1) image portion: the object of cognition (objective appearance), further as image-image and essential-image; (2) perceiving portion: the subject of cognition, able to illuminate the image; (3) self-aware portion (self-portion): the function on the substance that verifies the perceiving portion; (4) re-aware portion: the function that verifies the self-aware portion. Each of the eight consciousnesses and their concomitant mental factors has these four. The image is an “external” object manifested by inner consciousness (not a real outer object); the perceiving portion is subjective cognition; the self-aware portion is the consciousness-substance itself; the re-aware portion again verifies that substance's knowing.",
'fr': "Doctrine du Rien-que-conscience : la fonction cognitive de la conscience mentale a quatre divisions, surgissant dans la transformation de la conscience—(1) portion-image : l'objet de la connaissance (apparence objective), encore comme image-image et image-essentielle ; (2) portion percevante : le sujet de la connaissance, capable d'illuminer l'image ; (3) portion d'auto-connaissance (portion-substance) : la fonction sur la substance qui vérifie la portion percevante ; (4) portion de ré-connaissance : la fonction qui vérifie l'auto-connaissance. Chacune des huit consciences et de leurs facteurs concomitants a ces quatre. L'image est un objet « externe » manifesté par la conscience intérieure (non un objet extérieur réel) ; la portion percevante est la connaissance subjective ; l'auto-connaissance est la substance-conscience elle-même ; la ré-connaissance vérifie à nouveau ce connaître.",
'vi': "Giáo nghĩa Duy Thức tông: tác dụng nhận thức của tâm thức có bốn loại phân loại, sinh khởi khi thức biến—(1) tướng phần: đối tượng nhận thức (khách thể), lại chia ảnh tượng tướng phần và bản chất tướng phần; (2) kiến phần: chủ thể nhận thức, hay chiếu biết tướng phần; (3) tự chứng phần (tự thể phần): tác dụng trên tự thể chứng biết kiến phần; (4) chứng tự chứng phần: tác dụng chứng biết tự chứng phần. Tám thức và tâm sở tương ưng đều đủ bốn phần này. Tướng phần là ngoại cảnh do nội thức biến hiện (chẳng phải ngoại cảnh thật có); kiến phần là tác dụng nhận thức chủ quan; tự chứng phần là tự thể của thức; chứng tự chứng phần là tác dụng chứng biết lại tự chứng phần.",
}

D['三性'] = {
'en': "Also called the three self-natures: the imagined nature, the other-dependent nature, and the perfectly accomplished nature—the root of all Consciousness-Only doctrine. The Dharma-characteristics school takes consciousness-only as the Middle Way, showing neither emptiness alone nor existence alone. At the center is the other-dependent: all dharmas arise relying on causes and conditions. On these provisionally assembled dharmas, if beings cling and calculate them as a real self or real dharmas, that is the imagined nature; if they understand dependent arising and the lack of essential self-nature, that is the perfectly accomplished nature. The imagined is delusive existence in the emotional consciousness; the other-dependent is provisional existence from the union of conditions; the perfectly accomplished is suchness—complete, accomplished, and real. Cheng weishi lun fascicle 8: mind, mental factors, and what they manifest, arising from manifold conditions like illusions, are all other-dependent; fools' false grasping at self and dharmas is the imagined; on the other-dependent, emptying that false grasping reveals the true nature of consciousness, called the perfectly accomplished.",
'fr': "Aussi appelées les trois natures propres : la nature imaginée, la nature dépendante d'autrui et la nature parfaitement accomplie—racine de toute la doctrine du Rien-que-conscience. L'école des Caractéristiques prend le rien-que-conscience pour Voie du milieu, montrant ni la seule vacuité ni la seule existence. Au centre est le dépendant d'autrui : tous les dharmas surgissent en s'appuyant sur causes et conditions. Sur ces dharmas provisoirement assemblés, si les êtres s'y attachent et les calculent comme soi réel ou dharmas réels, c'est l'imaginé ; s'ils comprennent la coproduction conditionnée et l'absence de nature propre essentielle, c'est le parfaitement accompli. L'imaginé est l'existence illusoire dans la conscience émotionnelle ; le dépendant d'autrui est l'existence provisoire de l'union des conditions ; le parfaitement accompli est l'ainsité—complète, accomplie et réelle. Cheng weishi lun fasc. 8 : esprit, facteurs et ce qu'ils manifestent, surgissant de conditions multiples comme des illusions, sont tous dépendants d'autrui ; la fausse saisie des sots est l'imaginé ; sur le dépendant d'autrui, vider cette saisie révèle la nature véritable de la conscience, dite parfaitement accomplie.",
'vi': "Cũng gọi ba tự tính: biến kế sở chấp tính, y tha khởi tính, viên thành thật tính—căn bản hết thảy pháp nghĩa của Duy Thức tông. Pháp Tướng tông lấy duy thức làm trung đạo, chính hiển phi không phi hữu. Trung tâm là y tha khởi tính: các pháp đều nương nhân nhờ duyên mà khởi. Trên pháp giả hòa hợp nhân duyên ấy, nếu hữu tình chấp trước tính toán cho là thật ngã, thật pháp, đó là biến kế sở chấp tính; nếu rõ biết duyên khởi, đều không có bản chất tự tính, đó là viên thành thật tính. Biến kế là vọng hữu trên tình thức; y tha là giả hữu do nhân duyên hòa hợp; viên thành thật là chân như thật tính—viên mãn, thành tựu, chân thật. Thành Duy Thức Luận quyển 8: tâm, tâm sở và sở biến hiện, chúng duyên sinh nên như sự huyễn, hết thảy đều gọi y tha khởi tính; kẻ ngu ở đây ngang chấp ngã pháp, hết thảy đều gọi biến kế sở chấp; trên y tha khởi, cái vọng chấp ngã pháp đều không, cái không ấy hiển bày thật tính của thức v.v. gọi viên thành thật.",
}

D['遍计所执性'] = {
'en': "Also called the imagined mark; one of the three natures. Ordinary beings' deluded emotion thoroughly calculates (parikalpayati) the dharmas that arise from causes and conditions and clings to them as really existent—this is the imagined nature. People take the five aggregates, twelve bases, and eighteen elements as a real self and real dharmas; in fact all is “manifested by consciousness alone,” produced by deluded discrimination. Nanda divides that which imagines and that which is imagined; Dharmapāla and Sthiramati add a third door, the imagined nature itself. The orthodox view generally takes the sixth and seventh consciousnesses as that which imagines.",
'fr': "Aussi appelée marque imaginée ; l'une des trois natures. L'émotion trompeuse des êtres ordinaires calcule de façon exhaustive (parikalpayati) les dharmas nés des causes et conditions et s'y attache comme réellement existants—c'est la nature imaginée. On prend les cinq agrégats, douze bases et dix-huit éléments pour un soi réel et des dharmas réels ; en fait tout est « manifesté par la seule conscience », produit par la discrimination trompeuse. Nanda divise ce qui imagine et ce qui est imaginé ; Dharmapāla et Sthiramati ajoutent une troisième porte, la nature imaginée elle-même. La vue orthodoxe tient en général les sixième et septième consciences pour ce qui imagine.",
'vi': "Còn gọi biến kế sở chấp tướng; một trong ba tự tính. Vọng tình của phàm phu chu biến kế độ các pháp do nhân duyên sinh khởi, chấp lấy làm thật có—đó là biến kế sở chấp tính. Người thường cho ngũ uẩn, mười hai xứ, mười tám giới là thật ngã, thật pháp; thật ra hết thảy đều là “duy thức sở biến”, do hư vọng phân biệt của hữu tình tạo thành. Nan-đà chia năng biến kế và sở biến kế; Hộ Pháp, An Huệ thì chia năng biến kế, sở biến kế, biến kế sở chấp ba môn. Chính nghĩa chung lấy thức thứ sáu và thứ bảy làm năng biến kế.",
}

D['依他起性'] = {
'en': "Also other-dependent mark or dependent-arising self-nature; one of the three natures. “Other” means causes and conditions: dharmas that arise in dependence on them are other-dependent. It belongs to the conditioned; of the hundred dharmas all but the six unconditioned are included here. “Manifold conditions” means the four conditions: mind needs all four; form needs only cause-condition and predominant condition. Conditioned phenomena arise when conditions unite and cease when they disperse—hence existent yet not [truly] existent, nonexistent yet not [utterly] nonexistent, provisionally existent like an illusion. Divided into defiled other-dependent (contaminated) and pure other-dependent (uncontaminated); the pure may also be included under the perfectly accomplished. See Cheng weishi lun fascicle 8.",
'fr': "Aussi marque dépendante d'autrui ou nature propre de la coproduction ; l'une des trois natures. « Autrui » désigne causes et conditions : les dharmas qui naissent en en dépendant sont dépendants d'autrui. Cela relève du conditionné ; des cent dharmas, tous sauf les six inconditionnés y sont inclus. Les « conditions multiples » sont les quatre conditions : l'esprit les requiert toutes ; la forme n'a besoin que de la cause-condition et de la condition prédominante. Les phénomènes conditionnés naissent quand les conditions s'unissent et cessent quand elles se dispersent—d'où existant sans [vraiment] exister, inexistant sans [totalement] n'être pas, provisoirement existant comme une illusion. Divisé en dépendant d'autrui souillé (contaminé) et pur (non contaminé) ; le pur peut aussi relever du parfaitement accompli. Voir Cheng weishi lun fasc. 8.",
'vi': "Còn gọi y tha khởi tướng, duyên khởi tự tính; một trong ba tự tính. “Tha” chỉ nhân duyên; pháp nương nhân duyên mà sinh khởi gọi y tha khởi. Thuộc hữu vi pháp; trong bách pháp trừ sáu vô vi, chín mươi bốn pháp còn lại đều nhiếp vào đây. Chúng duyên chỉ bốn duyên; tâm pháp sinh khởi phải đủ bốn duyên, sắc pháp chỉ cần nhân duyên và tăng thượng duyên. Hết thảy hiện tượng hữu vi đều do nhân duyên hòa hợp mà sinh, ly tán thì diệt—nên hữu nhi phi hữu, vô nhi phi vô, như huyễn giả hữu. Lại chia nhiễm phần y tha (hữu lậu tạp nhiễm) và tịnh phần y tha (vô lậu thuần tịnh); tịnh phần y tha cũng có thể nhiếp vào viên thành thật tính. Xem Thành Duy Thức Luận quyển 8.",
}

D['圆成实性'] = {
'en': "Also perfectly accomplished mark; one of the three natures. Suchness has three qualities: completeness (its principle pervades everywhere), accomplishment (its substance abides constantly without arising-and-ceasing), and reality (its nature is constant and pervasive). It is the truth revealed by emptying the two hindrances of afflictions and of the knowable—the true essence of all dharmas—also called suchness, true mark, dharma-realm, dharma-nature. The true nature of dharmas revealed by the emptiness of self and of dharmas is the perfectly accomplished. Constantly being free of the imagined nature upon the other-dependent is precisely the perfectly accomplished.",
'fr': "Aussi marque parfaitement accomplie ; l'une des trois natures. L'ainsité a trois qualités : plénitude (son principe pénètre partout), accomplissement (sa substance demeure constamment sans naître-et-cesser) et réalité (sa nature est constante et pénétrante). C'est la vérité révélée en vidant les deux obstacles des afflictions et du connaissable—l'essence véritable de tous les dharmas—aussi appelée ainsité, marque vraie, réalme-de-dharma, nature-de-dharma. La nature vraie des dharmas révélée par la vacuité du soi et des dharmas est le parfaitement accompli. Être constamment libre de l'imaginé sur le dépendant d'autrui, c'est précisément le parfaitement accompli.",
'vi': "Còn gọi viên thành thật tướng; một trong ba tự tính. Chân như có ba tính chất: viên mãn (diệu lý chu biến), thành tựu (thực thể thường trụ không sinh diệt), chân thật (tính thường trụ biến thông). Viên thành thật tính là chân lý do không phiền não, sở tri hai chướng mà hiển—tức thật thể tính của các pháp—cũng gọi chân như, thật tướng, pháp giới, pháp tính. Thật tính của các pháp do ngã không, pháp không hiển bày chính là viên thành thật tính. Trên y tha khởi tính hằng lìa biến kế sở chấp tính, chính là viên thành thật tính.",
}

json.dump(D, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('手写核心入库后 defs_i18n =', len(D))
print('已有:', [k for k in ['末那识','见分','相分','自证分','证自证分','识体四分','三性','遍计所执性','依他起性','圆成实性'] if k in D])
