#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""试点：6 个核心名相释义的英/法/越翻译，写入 defs_i18n.json。"""
import json, os
BASE = os.path.dirname(__file__)

D = {}

D['法相'] = {
 'en': "Refers to the essential characteristics (the marks of essence, 體相) possessed by all dharmas, or to their meaning-content (the marks of meaning, 義相). The distinctive feature of the Consciousness-Only (Yogācāra) school lies in analyzing and classifying the characteristics of dharmas; hence it is also called the Dharma-characteristics school (Faxiang zong). See the \u201cChapter on the Characteristics of All Dharmas\u201d in the Saṃdhinirmocana-sūtra.",
 'fr': "Désigne les caractéristiques essentielles (les marques de l'essence, 體相) que possèdent tous les dharmas, ou leur contenu de sens (les marques du sens, 義相). La particularité de l'école du Rien-que-conscience (Yogācāra) réside dans l'analyse et la classification des caractéristiques des dharmas ; c'est pourquoi on l'appelle aussi l'école des Caractéristiques des dharmas (Faxiang zong). Voir le chapitre « Les caractéristiques de tous les dharmas » du Saṃdhinirmocana-sūtra.",
 'vi': "Chỉ tướng trạng bản chất (thể tướng) mà các pháp sở hữu, hoặc chỉ nội dung ý nghĩa (nghĩa tướng) của chúng. Đặc trưng của Duy Thức tông (Yogācāra) nằm ở việc phân tích và phân loại thuyết minh pháp tướng, nên còn gọi là Pháp Tướng tông. Xem phẩm “Nhất thiết pháp tướng” trong Kinh Giải Thâm Mật.",
}

D['刹那'] = {
 'en': "Translated as \u201ca single thought-moment,\u201d it is the smallest unit of time. The Huayan tanxuan ji, fascicle 18, says: \u201cA kṣaṇa is here called a thought-instant; within the span of a finger-snap there are sixty kṣaṇas.\u201d Xuanzang's Records of the Western Regions of the Great Tang, fascicle 2, says: \u201cThe shortest span of time is the kṣaṇa; 120 kṣaṇas make one tatkṣaṇa, 60 tatkṣaṇas make one lava, 30 lavas make one muhūrta, 5 muhūrtas make one kāla (\u2018period\u2019), and six periods complete one day-and-night.\u201d Converted into modern reckoning, one day-and-night equals 6,480,000 kṣaṇas, one hour 270,000 kṣaṇas, one minute 4,500 kṣaṇas, and one second 75 kṣaṇas.",
 'fr': "Traduit par « un seul instant de pensée », c'est la plus petite unité de temps. Le Huayan tanxuan ji, fascicule 18, dit : « Un kṣaṇa est ici appelé un instant de pensée ; le temps d'un claquement de doigts contient soixante kṣaṇa. » Les Mémoires sur les contrées occidentales des grands Tang de Xuanzang, fascicule 2, disent : « Le laps de temps le plus bref est le kṣaṇa ; 120 kṣaṇa font un tatkṣaṇa, 60 tatkṣaṇa font un lava, 30 lava font un muhūrta, 5 muhūrta font un kāla (une « période »), et six périodes forment un jour-et-nuit. » Converti en calcul moderne, un jour-et-nuit équivaut à 6 480 000 kṣaṇa, une heure à 270 000 kṣaṇa, une minute à 4 500 kṣaṇa, et une seconde à 75 kṣaṇa.",
 'vi': "Dịch là “một niệm”, là đơn vị thời gian nhỏ nhất. Hoa Nghiêm Thám Huyền Ký, quyển 18, nói: “Sát-na ở đây gọi là khoảnh niệm; trong khoảng một cái búng tay có sáu mươi sát-na.” Tam Tạng Huyền Trang trong Đại Đường Tây Vực Ký, quyển 2, nói: “Thời gian cực ngắn gọi là sát-na; 120 sát-na là một đát-sát-na, 60 đát-sát-na là một lạp-phược, 30 lạp-phược là một mâu-hô-lật-đa, 5 mâu-hô-lật-đa là một thời, sáu thời hợp thành một ngày một đêm.” Quy đổi theo cách tính hiện đại, một ngày đêm bằng 6.480.000 sát-na, một giờ bằng 270.000 sát-na, một phút bằng 4.500 sát-na, một giây bằng 75 sát-na.",
}

D['空性'] = {
 'en': "An alternative name for suchness (tathatā). The Sanskrit śūnyatā is rendered \u201cemptiness-nature.\u201d Suchness is the true substance free from the two graspings\u2014at a self and at dharmas; therefore, at the point where one cultivates the contemplation of emptiness and departs from these two graspings, the true substance of suchness vividly manifests. This true nature revealed on the basis of emptiness is called \u201cemptiness-nature\u201d (śūnyatā); it does not mean that the substance of suchness is [merely] empty. The Cheng weishi lun shuji, fascicle 1a, says: \u201cThe Sanskrit śūnya may be described as being like space; it is termed śūnyatā. Such emptiness-nature is precisely the true nature revealed by the two [kinds of] emptiness. Thus \u2018emptiness\u2019 is spoken of from the side of that which reveals; the nature [revealed by] the two emptinesses is named by way of a dependent (tatpuruṣa) compound. To say merely \u2018suchness is empty\u2019 would not fully accord with the principle.\u201d",
 'fr': "Autre nom de l'ainsité (tathatā). Le sanskrit śūnyatā se traduit par « nature de vacuité ». L'ainsité est la substance véritable, libérée des deux saisies\u2014celle d'un soi et celle des dharmas ; c'est pourquoi, là où l'on cultive la contemplation de la vacuité et se libère de ces deux saisies, la substance véritable de l'ainsité se manifeste avec évidence. Cette nature véritable révélée sur la base de la vacuité est appelée « nature de vacuité » (śūnyatā) ; cela ne signifie pas que la substance de l'ainsité soit [seulement] vide. Le Cheng weishi lun shuji, fascicule 1a, dit : « Le sanskrit śūnya peut être décrit comme semblable à l'espace ; on le nomme śūnyatā. Une telle nature de vacuité est précisément la nature véritable révélée par les deux [sortes de] vacuité. Ainsi « vacuité » se dit du côté de ce qui révèle ; la nature [révélée par] les deux vacuités est nommée selon un composé de dépendance (tatpuruṣa). Dire simplement « l'ainsité est vide » ne serait pas pleinement conforme au principe. »",
 'vi': "Tên gọi khác của chân như (tathatā). Phạn ngữ śūnyatā (thuấn-nhã-đa) dịch là “không tính”. Chân như là thật thể lìa hai chấp\u2014chấp ngã và chấp pháp; vì thế, nơi tu quán không mà lìa được hai chấp ấy, thật thể của chân như hiển lộ rõ ràng. Cái thật tính nương nơi “không” mà hiển bày này gọi là “không tính” (śūnyatā); chứ không phải nói thể của chân như là không. Thành Duy Thức Luận Thuật Ký, quyển 1 (bản thượng), nói: “Phạn ngữ śūnya có thể nói như hư không, gọi là śūnyatā. Không tính như vậy chính là thật tính do hai không hiển bày. Cho nên nói ‘không’ là nói từ phía năng hiển; tính của hai không được đặt tên theo cách y-sĩ thích (tatpuruṣa). Nếu chỉ nói ‘chân như là không’ thì chưa trọn hợp với lý.”",
}

D['熏习'] = {
 'en': "The good and evil actions expressed through our body and speech, or the good and evil thoughts arising in our mind-consciousness, leave their \u201cvapor-trace\u201d within the ālaya-consciousness\u2014like incense perfuming clothing; this is called perfuming (vāsanā). The actions produced through our body, speech, and mind are called \u201cpresent activity\u201d (現行). In other words, the eighth, ālaya, consciousness is able to preserve the traces of experience\u2014these are the \u201cvapor\u201d or seeds. And the traces of experience (the deeds of body, speech, and mind) can influence a person's future character and conduct: this is perfuming. When one is habituated to doing good, that good conduct is a kind of perfuming; when one is habituated to doing evil, that evil conduct too is a kind of perfuming. Perfuming is not something deliberately contrived; it proceeds spontaneously, without one's being aware of it\u2014like a person walking through mist, who does not intend to wet his clothes and does not feel them getting wet, yet in fact his clothes have become saturated with moisture. The Awakening of Mahāyāna Faith says: \u201cAs for the meaning of perfuming: worldly clothing has, in itself, no fragrance, but if a person perfumes it with incense, it then carries the scent.\u201d",
 'fr': "Les actes bons ou mauvais exprimés par notre corps et notre parole, ou les pensées bonnes ou mauvaises surgissant dans notre conscience mentale, laissent leur « trace-vapeur » au sein de la conscience-ālaya\u2014comme l'encens parfume les vêtements ; c'est ce qu'on appelle l'imprégnation (vāsanā). Les actes produits par notre corps, notre parole et notre mental sont appelés « activité manifeste » (現行). Autrement dit, la huitième conscience, l'ālaya, est capable de conserver les traces de l'expérience\u2014ce sont la « vapeur » ou les semences. Et les traces de l'expérience (les actes du corps, de la parole et du mental) peuvent influencer le caractère et la conduite futurs d'une personne : c'est l'imprégnation. Qui est habitué à faire le bien, cette bonne conduite est une imprégnation ; qui est habitué à faire le mal, cette mauvaise conduite en est également une. L'imprégnation n'est pas délibérément produite ; elle s'opère spontanément, à notre insu\u2014comme une personne marchant dans la brume, qui n'a pas l'intention de mouiller ses vêtements et ne les sent pas se mouiller, alors qu'en réalité ils sont déjà imprégnés d'humidité. Le Traité de l'Éveil de la foi dans le Mahāyāna dit : « Quant au sens de l'imprégnation : un vêtement du monde n'a en lui-même aucun parfum, mais si quelqu'un l'imprègne d'encens, il porte alors une odeur parfumée. »",
 'vi': "Những hành vi thiện ác biểu hiện qua thân và khẩu của chúng ta, hoặc những tư tưởng thiện ác khởi lên nơi ý thức, để lại “khí phần” của chúng trong thức A-lại-da\u2014như hương xông ướp vào áo; đó gọi là huân tập (vāsanā). Còn các hành vi do thân, khẩu, ý của chúng ta khởi lên thì gọi là hiện hành (現行). Nói cách khác, thức thứ tám A-lại-da có thể giữ lại dấu vết của kinh nghiệm, đó chính là khí phần hay chủng tử. Mà dấu vết của kinh nghiệm (hành vi của thân, khẩu, ý) có thể ảnh hưởng đến tính cách và hành vi tương lai của một người: đó là huân tập. Một người quen làm thiện, thiện hành ấy là một thứ huân tập; một người quen làm ác, ác hành ấy cũng là một thứ huân tập. Huân tập không phải cố ý tạo thành, mà tiến hành một cách tự nhiên, không hay không biết\u2014như người đi trong sương mù, không cố ý làm ướt áo, cũng không cảm thấy áo bị ướt, nhưng thực ra áo đã đẫm hơi ẩm. Đại Thừa Khởi Tín Luận nói: “Nghĩa của huân tập: áo quần thế gian vốn thật không có hương, nhưng nếu người ta lấy hương xông ướp thì liền có mùi hương.”",
}

D['涅槃'] = {
 'en': "Also transliterated niyuan or nirvāṇa; rendered by meaning as extinction, quiescent extinction, extinction-crossing (deliverance), or no-arising. It is synonymous with such terms as \u201ccessation through discrimination\u201d (pratisaṃkhyā-nirodha), \u201cfreedom from bondage,\u201d and \u201cliberation.\u201d It also appears as parinirvāṇa and mahāparinirvāṇa. Originally it meant \u201cblowing out,\u201d or the state of a fire gradually being extinguished; later it came to denote the state in which the fire of the afflictions is completely extinguished and the wisdom of awakening (i.e., bodhi) is perfected. This is the realm of awakening that transcends birth-and-death (the realm of delusion), and it is also the ultimate goal of Buddhist practice; therefore, as a mark of the Buddhist teaching, it is listed as one of the Dharma-seals, called \u201cnirvāṇa is quiescence.\u201d Sectarian (Abhidharma) Buddhism took nirvāṇa to be the state of having extinguished the afflictions. Within this there is a further division into nirvāṇa with remainder and nirvāṇa without remainder: the former is the case where the afflictions are severed yet the physical body (i.e., the remaining bodily support) still exists; the latter is the state of \u201cbody reduced to ashes and cognition extinguished,\u201d that is, the situation in which everything returns to extinction. The physical death of the Buddha who appeared in this world as a human (specifically Śākyamuni) is called nirvāṇa, parinirvāṇa, or mahāparinirvāṇa. Entering nirvāṇa is also called \u201centering extinction\u201d or \u201cthe fuel exhausted, the fire extinguished\u201d (the fuel symbolizing the Buddha's body or the conditions for teaching, the fire symbolizing wisdom or the Buddha's body). Nirvāṇa originally referred to Śākyamuni's attainment of the Way, but nowadays it is generally used in the sense of nirvāṇa without remainder.",
 'fr': "Aussi transcrit niyuan ou nirvāṇa ; traduit par le sens comme extinction, extinction quiescente, extinction-passage (délivrance), ou non-naissance. Synonyme de termes tels que « cessation par discrimination » (pratisaṃkhyā-nirodha), « affranchissement des liens » et « libération ». Apparaît aussi sous les formes parinirvāṇa et mahāparinirvāṇa. À l'origine, le mot signifiait « souffler pour éteindre », ou l'état d'un feu qui s'éteint peu à peu ; il en vint ensuite à désigner l'état où le feu des afflictions est entièrement éteint et où la sagesse de l'éveil (c'est-à-dire la bodhi) est parachevée. C'est le domaine de l'éveil qui transcende le cycle des naissances et des morts (le domaine de l'illusion), et c'est aussi le but ultime de la pratique bouddhique ; c'est pourquoi, en tant que marque de l'enseignement, il figure parmi les sceaux du Dharma sous le nom de « nirvāṇa est quiétude ». Le bouddhisme des écoles (Abhidharma) tenait le nirvāṇa pour l'état d'extinction des afflictions. On y distingue en outre le nirvāṇa avec reste et le nirvāṇa sans reste : le premier est le cas où les afflictions sont tranchées mais où le corps physique (le support corporel résiduel) subsiste encore ; le second est l'état de « corps réduit en cendres et cognition éteinte », c'est-à-dire la situation où tout retourne à l'extinction. La mort physique du Buddha apparu en ce monde sous forme humaine (en particulier Śākyamuni) est appelée nirvāṇa, parinirvāṇa ou mahāparinirvāṇa. Entrer dans le nirvāṇa se dit aussi « entrer dans l'extinction » ou « le combustible épuisé, le feu éteint » (le combustible symbolisant le corps du Buddha ou les conditions d'enseignement, le feu symbolisant la sagesse ou le corps du Buddha). Nirvāṇa désignait à l'origine l'accès de Śākyamuni à la Voie, mais on l'emploie aujourd'hui généralement au sens de nirvāṇa sans reste.",
 'vi': "Cũng phiên âm là nê-hoàn, niết-bàn-na; dịch nghĩa là diệt, tịch diệt, diệt độ, vô sinh. Đồng nghĩa với các từ như trạch diệt (pratisaṃkhyā-nirodha), ly hệ, giải thoát. Hoặc gọi là bát-niết-bàn, đại bát-niết-bàn. Vốn nghĩa là thổi tắt, hoặc chỉ trạng thái lửa dần dần tắt lịm; về sau chuyển sang chỉ cảnh giới mà lửa phiền não cháy sạch, hoàn thành trí tuệ giác ngộ (tức bồ-đề). Đây là cảnh giới giác ngộ vượt khỏi sinh tử (cõi mê), cũng là mục đích thực hành tối hậu của Phật giáo; vì thế, biểu thị đặc trưng của Phật giáo, nó được liệt vào một trong các pháp ấn, gọi là “niết-bàn tịch tĩnh”. Phật giáo bộ phái xem niết-bàn là trạng thái diệt trừ phiền não. Trong đó lại chia thành hữu dư y niết-bàn và vô dư y niết-bàn: cái trước là trường hợp tuy đã đoạn phiền não nhưng thân xác (tức thân y còn sót lại) vẫn còn; cái sau là trạng thái “thiêu thân diệt trí”, tức chỉ tình huống hết thảy quy về diệt vô. Cái chết thân xác của đức Phật thị hiện làm người ở thế gian này (đặc chỉ đức Thích Tôn) được gọi là niết-bàn, bát-niết-bàn, đại bát-niết-bàn. Nhập niết-bàn còn gọi là nhập diệt, “củi hết lửa tắt” (củi ví cho thân Phật hoặc cơ duyên, lửa ví cho trí tuệ hoặc thân Phật). Niết-bàn nguyên nghĩa chỉ sự thành đạo của đức Thích Tôn, nhưng nay phần lớn đều dùng theo nghĩa vô dư y niết-bàn.",
}

D['缘起'] = {
 'en': "Dependent origination (Skt. pratītya-samutpāda) means \u201carising through mutual relation.\u201d This is a fundamental doctrine of Buddhism and the Buddha's basic view of life and existence. The Buddha held that in the phenomenal world there is nothing that exists eternally and nothing that exists in isolation; all things arise and exist through mutual relation and dependence. Thus the Saṃyukta-āgama (sūtra 293) explains dependent origination: \u201cBecause this exists, that exists; because this arises, that arises; because this does not exist, that does not exist; because this ceases, that ceases.\u201d That is, all arising and existence come about through mutual relation. This relational dependence is of two kinds: one is the relation of simultaneous co-dependence manifested in space; the other is the relation of cause and effect across different times, manifested in time. The cause-and-effect relation across time is the so-called \u201cbecause this arises, that arises; because this ceases, that ceases\u201d\u2014this being cause and that being effect. The simultaneous relation of co-dependence is the so-called \u201cbecause this exists, that exists; because this does not exist, that does not exist\u201d\u2014this being primary and that being subordinate. Yet this causal and primary-subordinate ordering is not absolute; viewed from another angle, cause and effect, primary and subordinate, can be reversed. Hence the sūtra says: \u201cThe Buddha said: it is like two sheaves of reeds that can stand only by leaning on each other. Friends, conditioned by name-and-form there is consciousness; conditioned by consciousness there is name-and-form; when this arises, that arises; when this ceases, that ceases\u2014just so. Friends, of two sheaves of reeds, remove this one and that one cannot stand; remove that one and this one cannot stand. When name-and-form ceases, consciousness ceases; when consciousness ceases, name-and-form ceases\u2014just so.\u201d Some say that \u201cdependent origination\u201d (older translation: causes-and-conditions) and \u201cdependent arising\u201d (缘生) may be used interchangeably; in fact there remains a distinction: dependent origination is named from the side of the cause, while dependent arising is named from the side of the effect. Liangbi's commentary says: \u201cAs for \u2018dependent arising,\u2019 \u2018condition\u2019 means the manifold conditions, and \u2018arising\u2019 means coming forth; all conditioned dharmas arise from conditions.\u201d",
 'fr': "La coproduction conditionnée (skt. pratītya-samutpāda) signifie « surgir par relation mutuelle ». C'est une doctrine fondamentale du bouddhisme et la vision de base qu'a le Buddha de la vie et de l'existence. Le Buddha soutenait que, dans le monde phénoménal, rien n'existe de façon éternelle ni de façon isolée ; tout surgit et existe par relation et dépendance mutuelles. Ainsi le Saṃyukta-āgama (sūtra 293) explique la coproduction conditionnée : « Ceci étant, cela est ; ceci surgissant, cela surgit ; ceci n'étant pas, cela n'est pas ; ceci cessant, cela cesse. » Autrement dit, tout surgissement et toute existence adviennent par relation mutuelle. Cette dépendance relationnelle est de deux sortes : l'une est la relation de co-dépendance simultanée manifestée dans l'espace ; l'autre est la relation de cause à effet à travers des temps différents, manifestée dans le temps. La relation causale à travers le temps est le fameux « ceci surgissant, cela surgit ; ceci cessant, cela cesse »\u2014ceci étant la cause et cela l'effet. La relation simultanée de co-dépendance est le fameux « ceci étant, cela est ; ceci n'étant pas, cela n'est pas »\u2014ceci étant le principal et cela le subordonné. Or cet ordre de cause et d'effet, de principal et de subordonné, n'est pas absolu ; sous un autre angle, cause et effet, principal et subordonné peuvent être inversés. C'est pourquoi le sūtra dit : « Le Buddha dit : c'est comme deux gerbes de roseaux qui ne peuvent tenir debout qu'en s'appuyant l'une sur l'autre. Amis, conditionnée par le nom-et-forme il y a la conscience ; conditionné par la conscience il y a le nom-et-forme ; ceci surgissant, cela surgit ; ceci cessant, cela cesse\u2014ainsi en est-il. Amis, de deux gerbes de roseaux, ôtez celle-ci et celle-là ne tient plus ; ôtez celle-là et celle-ci ne tient plus. Le nom-et-forme cessant, la conscience cesse ; la conscience cessant, le nom-et-forme cesse\u2014ainsi en est-il. » Certains disent que « coproduction conditionnée » (ancienne traduction : causes-et-conditions) et « production conditionnée » (缘生) sont interchangeables ; en réalité une distinction subsiste : la coproduction conditionnée est nommée du côté de la cause, la production conditionnée du côté de l'effet. Le commentaire de Liangbi dit : « Pour « production conditionnée », « condition » désigne les multiples conditions, et « production » signifie surgir ; tous les dharmas conditionnés surgissent des conditions. »",
 'vi': "Duyên khởi (Phạn: pratītya-samutpāda) nghĩa là “do nương nhau mà sinh khởi”. Đây là lý thuyết căn bản của Phật giáo, là cái nhìn cơ bản của đức Phật về sinh mệnh và sự tồn tại. Đức Phật cho rằng, trong thế giới hiện tượng, không có sự vật nào tồn tại vĩnh hằng, cũng không có sự vật nào tồn tại cô lập; hết thảy đều nương nhau, đối đãi nhau mà sinh khởi và tồn tại. Vì thế Kinh Tạp A-hàm (kinh 293) giải thích duyên khởi rằng: “Cái này có nên cái kia có; cái này sinh nên cái kia sinh; cái này không nên cái kia không; cái này diệt nên cái kia diệt.” Tức là hết thảy sự sinh khởi, tồn tại đều do nương nhau đối đãi mà có. Mối quan hệ nương đãi này có hai loại: một là quan hệ đồng thời nương tựa hiện bày qua không gian; hai là quan hệ nhân quả khác thời hiện bày qua thời gian. Quan hệ nhân quả khác thời tức là “cái này sinh nên cái kia sinh, cái này diệt nên cái kia diệt”\u2014cái này là nhân, cái kia là quả. Quan hệ đồng thời nương tựa tức là “cái này có nên cái kia có, cái này không nên cái kia không”\u2014cái này là chủ, cái kia là tùy. Nhưng cái nhân quả chủ tùy ấy không phải là tuyệt đối; đổi một góc nhìn, nhân quả chủ tùy lại có thể đảo ngược. Cho nên kinh nói: “Phật dạy: ví như hai bó lau, nương tựa nhau mới đứng vững được. Này các bạn, duyên danh sắc mà có thức, duyên thức mà có danh sắc; cái này sinh thì cái kia sinh, cái này diệt thì cái kia diệt, đúng là như vậy. Này các bạn, hai bó lau, lấy đi bó này thì bó kia không dựng đứng được; lấy đi bó kia thì bó này cũng không dựng đứng được. Danh sắc diệt thì thức diệt, thức diệt thì danh sắc diệt, đúng là như vậy.” Có người nói duyên khởi (dịch cũ là nhân duyên) và duyên sinh có thể dùng thông nhau; thật ra vẫn có chỗ khác biệt: duyên khởi lập danh từ phía nhân, duyên sinh lập danh từ phía quả. Sớ của Lương Bí nói: “Nói ‘duyên sinh’: ‘duyên’ là các duyên, ‘sinh’ là khởi; các pháp hữu vi đều từ duyên mà sinh.”",
}

json.dump(D, open(os.path.join(BASE, 'defs_i18n.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('写入 defs_i18n.json：', len(D), '条')
